/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.arruolamento.preferenze;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2018-11-05T17:23:28.392+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/SetPreferenzeArruolabilita/", name = "CCSetPreferenzeArruolabilitaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CCSetPreferenzeArruolabilitaServicePortType {

    @WebMethod(operationName = "Set", action = "http://dmacc.csi.it/SetPreferenzeArruolabilita/Set")
    @Action(input = "http://dmacc.csi.it/SetPreferenzeArruolabilita/Set", output = "http://dmacc.csi.it/SetPreferenzeArruolabilita/SetPreferenzeArruolabilita/SetResponse")
    @RequestWrapper(localName = "Set", targetNamespace = "http://dmacc.csi.it/SetPreferenzeArruolabilita/", className = "it.csi.apisan.apisanfse.integration.arruolamento.preferenze.Set")
    @ResponseWrapper(localName = "setResponse", targetNamespace = "http://dmacc.csi.it", className = "it.csi.apisan.apisanfse.integration.arruolamento.preferenze.SetResponse")
    @WebResult(name = "inserimentoAvvenuto", targetNamespace = "http://dmacc.csi.it")
    public java.lang.String set(
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        java.lang.String codiceFiscale
    );
}
