/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanfse.integration.etichette.dmacc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-07T12:03:11.127+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class EtichetteService_EtichettePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "EtichetteService");

    private EtichetteService_EtichettePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EtichetteService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EtichetteService_Service ss = new EtichetteService_Service(wsdlURL, SERVICE_NAME);
        EtichetteService port = ss.getEtichettePort();  
        
        {
        System.out.println("Invoking associaDisassociaEtichette...");
        it.csi.apisan.apisanfse.integration.etichette.dmacc.AssociaDisassociaEtichetteRequest _associaDisassociaEtichette_associaDisassociaEtichette = null;
        it.csi.apisan.apisanfse.integration.etichette.dmacc.EtichetteResponse _associaDisassociaEtichette__return = port.associaDisassociaEtichette(_associaDisassociaEtichette_associaDisassociaEtichette);
        System.out.println("associaDisassociaEtichette.result=" + _associaDisassociaEtichette__return);


        }
        {
        System.out.println("Invoking getListaEtichette...");
        it.csi.apisan.apisanfse.integration.etichette.dma.RichiedenteInfo _getListaEtichette_richiedente = null;
        java.lang.String _getListaEtichette_cfPaziente = "";
        it.csi.apisan.apisanfse.integration.etichette.dma.TipoEtichetta _getListaEtichette_tipoEtichetta = null;
        javax.xml.ws.Holder<java.util.List<it.csi.apisan.apisanfse.integration.etichette.dmacc.Errore>> _getListaEtichette_errori = new javax.xml.ws.Holder<java.util.List<it.csi.apisan.apisanfse.integration.etichette.dmacc.Errore>>();
        javax.xml.ws.Holder<it.csi.apisan.apisanfse.integration.etichette.dmacc.RisultatoCodice> _getListaEtichette_esito = new javax.xml.ws.Holder<it.csi.apisan.apisanfse.integration.etichette.dmacc.RisultatoCodice>();
        javax.xml.ws.Holder<it.csi.apisan.apisanfse.integration.etichette.dma.ListaEtichette> _getListaEtichette_listaEtichette = new javax.xml.ws.Holder<it.csi.apisan.apisanfse.integration.etichette.dma.ListaEtichette>();
        port.getListaEtichette(_getListaEtichette_richiedente, _getListaEtichette_cfPaziente, _getListaEtichette_tipoEtichetta, _getListaEtichette_errori, _getListaEtichette_esito, _getListaEtichette_listaEtichette);

        System.out.println("getListaEtichette._getListaEtichette_errori=" + _getListaEtichette_errori.value);
        System.out.println("getListaEtichette._getListaEtichette_esito=" + _getListaEtichette_esito.value);
        System.out.println("getListaEtichette._getListaEtichette_listaEtichette=" + _getListaEtichette_listaEtichette.value);

        }
        {
        System.out.println("Invoking updateEtichettaPersonale...");
        it.csi.apisan.apisanfse.integration.etichette.dmacc.UpdateEtichettaRequest _updateEtichettaPersonale_updateEtichettaPersonale = null;
        it.csi.apisan.apisanfse.integration.etichette.dmacc.EtichetteResponse _updateEtichettaPersonale__return = port.updateEtichettaPersonale(_updateEtichettaPersonale_updateEtichettaPersonale);
        System.out.println("updateEtichettaPersonale.result=" + _updateEtichettaPersonale__return);


        }
        {
        System.out.println("Invoking setEtichettaPersonale...");
        it.csi.apisan.apisanfse.integration.etichette.dmacc.SetEtichettaRequest _setEtichettaPersonale_setEtichettaPersonale = null;
        it.csi.apisan.apisanfse.integration.etichette.dmacc.EtichetteResponse _setEtichettaPersonale__return = port.setEtichettaPersonale(_setEtichettaPersonale_setEtichettaPersonale);
        System.out.println("setEtichettaPersonale.result=" + _setEtichettaPersonale__return);


        }

        System.exit(0);
    }

}
