/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.etichette.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-07T12:03:11.179+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "EtichetteService")
@XmlSeeAlso({it.csi.apisan.apisanfse.integration.etichette.dma.ObjectFactory.class, ObjectFactory.class})
public interface EtichetteService {

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "associaDisassociaEtichetteResponse", targetNamespace = "http://dmacc.csi.it/", partName = "associaDisassociaEtichetteResponse")
    public EtichetteResponse associaDisassociaEtichette(
        @WebParam(partName = "associaDisassociaEtichette", name = "associaDisassociaEtichette", targetNamespace = "http://dmacc.csi.it/")
        AssociaDisassociaEtichetteRequest associaDisassociaEtichette
    );

    @WebMethod
    @RequestWrapper(localName = "getListaEtichette", targetNamespace = "http://dmacc.csi.it/", className = "it.csi.apisan.apisanfse.integration.etichette.dmacc.GetListaEtichetteRequest")
    @ResponseWrapper(localName = "GetListaEtichetteResponse", targetNamespace = "http://dmacc.csi.it/", className = "it.csi.apisan.apisanfse.integration.etichette.dmacc.GetListaEtichetteResponse")
    public void getListaEtichette(
        @WebParam(name = "richiedente", targetNamespace = "")
        it.csi.apisan.apisanfse.integration.etichette.dma.RichiedenteInfo richiedente,
        @WebParam(name = "cfPaziente", targetNamespace = "")
        java.lang.String cfPaziente,
        @WebParam(name = "tipoEtichetta", targetNamespace = "")
        it.csi.apisan.apisanfse.integration.etichette.dma.TipoEtichetta tipoEtichetta,
        @WebParam(mode = WebParam.Mode.OUT, name = "errori", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<it.csi.apisan.apisanfse.integration.etichette.dmacc.Errore>> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "esito", targetNamespace = "")
        javax.xml.ws.Holder<RisultatoCodice> esito,
        @WebParam(mode = WebParam.Mode.OUT, name = "listaEtichette", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.apisan.apisanfse.integration.etichette.dma.ListaEtichette> listaEtichette
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateEtichettaPersonaleResponse", targetNamespace = "http://dmacc.csi.it/", partName = "updateEtichettaPersonaleResponse")
    public EtichetteResponse updateEtichettaPersonale(
        @WebParam(partName = "updateEtichettaPersonale", name = "updateEtichettaPersonale", targetNamespace = "http://dmacc.csi.it/")
        UpdateEtichettaRequest updateEtichettaPersonale
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "setEtichettaPersonaleResponse", targetNamespace = "http://dmacc.csi.it/", partName = "setEtichettaPersonaleResponse")
    public EtichetteResponse setEtichettaPersonale(
        @WebParam(partName = "setEtichettaPersonale", name = "setEtichettaPersonale", targetNamespace = "http://dmacc.csi.it/")
        SetEtichettaRequest setEtichettaPersonale
    );
}
