/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.celiachia.celiachiabesrv.business.endpoint;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-12-22T17:10:31.147+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class InterfacciaCeliachiaGocPortType_InterfacciaCeliachiaGocHttpsSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://endpoint.business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaGoc");

    private InterfacciaCeliachiaGocPortType_InterfacciaCeliachiaGocHttpsSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InterfacciaCeliachiaGoc.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InterfacciaCeliachiaGoc ss = new InterfacciaCeliachiaGoc(wsdlURL, SERVICE_NAME);
        InterfacciaCeliachiaGocPortType port = ss.getInterfacciaCeliachiaGocHttpsSoap11Endpoint();  
        
        {
        System.out.println("Invoking verificaErogazioniFarmacie...");
        it.csi.celiachia.celiachiabesrv.input.xsd.VerificaErogazioniFarmacie _verificaErogazioniFarmacie_input = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.VerificaErogazioniFarmacieResponse _verificaErogazioniFarmacie__return = port.verificaErogazioniFarmacie(_verificaErogazioniFarmacie_input);
        System.out.println("verificaErogazioniFarmacie.result=" + _verificaErogazioniFarmacie__return);


        }
        {
        System.out.println("Invoking usaPinDaQRCodeGOC...");
        it.csi.celiachia.celiachiabesrv.input.xsd.UsaPinRequest _usaPinDaQRCodeGOC_usaPinInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.UsaPinResponse _usaPinDaQRCodeGOC__return = port.usaPinDaQRCodeGOC(_usaPinDaQRCodeGOC_usaPinInput);
        System.out.println("usaPinDaQRCodeGOC.result=" + _usaPinDaQRCodeGOC__return);


        }
        {
        System.out.println("Invoking ricercaErogazioniAssistito...");
        it.csi.celiachia.celiachiabesrv.input.xsd.ElencoErogRequest _ricercaErogazioniAssistito_elencoErogInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.ElencoErogResponse _ricercaErogazioniAssistito__return = port.ricercaErogazioniAssistito(_ricercaErogazioniAssistito_elencoErogInput);
        System.out.println("ricercaErogazioniAssistito.result=" + _ricercaErogazioniAssistito__return);


        }
        {
        System.out.println("Invoking bckrigPinGOC...");
        it.csi.celiachia.celiachiabesrv.input.xsd.RigeneraPinRequest _bckrigPinGOC_saldoBuonoInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.RigeneraPinResponse _bckrigPinGOC__return = port.bckrigPinGOC(_bckrigPinGOC_saldoBuonoInput);
        System.out.println("bckrigPinGOC.result=" + _bckrigPinGOC__return);


        }
        {
        System.out.println("Invoking verificaSaldoAssistito...");
        it.csi.celiachia.celiachiabesrv.input.xsd.SaldoBuonoRequest _verificaSaldoAssistito_saldoBuonoInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.SaldoBuonoResponse _verificaSaldoAssistito__return = port.verificaSaldoAssistito(_verificaSaldoAssistito_saldoBuonoInput);
        System.out.println("verificaSaldoAssistito.result=" + _verificaSaldoAssistito__return);


        }
        {
        System.out.println("Invoking getPinAssistito...");
        it.csi.celiachia.celiachiabesrv.input.xsd.PinGocRequest _getPinAssistito_pinGocInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.PinGocResponse _getPinAssistito__return = port.getPinAssistito(_getPinAssistito_pinGocInput);
        System.out.println("getPinAssistito.result=" + _getPinAssistito__return);


        }
        {
        System.out.println("Invoking rigeneraPinAssistito...");
        it.csi.celiachia.celiachiabesrv.input.xsd.RigeneraPinRequest _rigeneraPinAssistito_rigeneraPinInput = null;
        it.csi.celiachia.celiachiabesrv.output.xsd.RigeneraPinResponse _rigeneraPinAssistito__return = port.rigeneraPinAssistito(_rigeneraPinAssistito_rigeneraPinInput);
        System.out.println("rigeneraPinAssistito.result=" + _rigeneraPinAssistito__return);


        }

        System.exit(0);
    }

}
