/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.operatori.def.opessanws.opessan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-07-21T14:03:08.387+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://opessan.opessanws.def.csi.it/", name = "ElencoOperatiori")
@XmlSeeAlso({it.csi.operatori.dto.opessanws.opessan.common.response.ObjectFactory.class, it.csi.operatori.dto.opessanws.opessan.common.request.ObjectFactory.class, ObjectFactory.class})
public interface ElencoOperatiori {

    @WebMethod
    @RequestWrapper(localName = "findOperatoriPerAssociazione", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.def.opessanws.opessan.FindOperatoriPerAssociazione")
    @ResponseWrapper(localName = "findOperatoriPerAssociazioneResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.def.opessanws.opessan.FindOperatoriPerAssociazioneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.operatori.def.opessanws.opessan.FindOperatoriPerAssociazioneResponse.Return findOperatoriPerAssociazione(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.operatori.def.opessanws.opessan.FindOperatoriPerAssociazione.Arg0 arg0
    );
}
