/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.screening.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-18T13:29:41.962+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "ScreeningService")
@XmlSeeAlso({it.csi.apisan.apisanfse.integration.screening.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScreeningService {

    @WebMethod
    @WebResult(name = "getScreeningResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getScreeningResponse")
    public ScreeningResponse getScreening(
        @WebParam(partName = "getScreening", name = "getScreening", targetNamespace = "http://dmacc.csi.it/")
        ScreeningRequest getScreening
    );
}
