/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.screening.dmacc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-18T13:29:41.966+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "ScreeningService", 
                  wsdlLocation = "file:/C:/Users/Sestu/AppData/Local/Temp/tempdir3774960420213058414.tmp/ScreeningService_1.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class ScreeningService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "ScreeningService");
    public final static QName ScreeningServicePort = new QName("http://dmacc.csi.it/", "ScreeningServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Sestu/AppData/Local/Temp/tempdir3774960420213058414.tmp/ScreeningService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScreeningService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Sestu/AppData/Local/Temp/tempdir3774960420213058414.tmp/ScreeningService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScreeningService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScreeningService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScreeningService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreeningService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreeningService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreeningService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ScreeningService
     */
    @WebEndpoint(name = "ScreeningServicePort")
    public ScreeningService getScreeningServicePort() {
        return super.getPort(ScreeningServicePort, ScreeningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScreeningService
     */
    @WebEndpoint(name = "ScreeningServicePort")
    public ScreeningService getScreeningServicePort(WebServiceFeature... features) {
        return super.getPort(ScreeningServicePort, ScreeningService.class, features);
    }

}
