/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanpresc.soap.sar.brokerservice;

import it.csi.apisan.apisanpresc.common.ApiSanPrescConstants;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-09-30T16:20:09.197+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "BrokerService", 
                  wsdlLocation = ApiSanPrescConstants.SAR_BROKERSERVICE_SOL_WSDL,
                  targetNamespace = "http://relbl.csi.it/") 
public class BrokerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://relbl.csi.it/", "BrokerService");
    public final static QName BrokerServicePort = new QName("http://relbl.csi.it/", "BrokerServicePort");
    static {
        URL url = null;
        try {
            url = new URL(ApiSanPrescConstants.SAR_BROKERSERVICE_SOL_ENDPOINT);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BrokerService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Work/CSIPiemonte/APISAN/apisanpresc/src/java/it/csi/apisan/apisanpresc/soap/sar/brokerservice/BrokerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BrokerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BrokerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrokerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BrokerService
     */
    @WebEndpoint(name = "BrokerServicePort")
    public BrokerService getBrokerServicePort() {
        return super.getPort(BrokerServicePort, BrokerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrokerService
     */
    @WebEndpoint(name = "BrokerServicePort")
    public BrokerService getBrokerServicePort(WebServiceFeature... features) {
        return super.getPort(BrokerServicePort, BrokerService.class, features);
    }

}
