/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanpresc.soap.sar.brokerservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-09-30T16:20:09.131+02:00
 * Generated source version: 2.7.14
 * 
 */
public final class BrokerService_BrokerServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://relbl.csi.it/", "BrokerService");

    private BrokerService_BrokerServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BrokerService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BrokerService_Service ss = new BrokerService_Service(wsdlURL, SERVICE_NAME);
        BrokerService port = ss.getBrokerServicePort();  
        
        {
        System.out.println("Invoking cacheDelete...");
        java.lang.String _cacheDelete_arg0 = "";
        port.cacheDelete(_cacheDelete_arg0);


        }
        {
        System.out.println("Invoking decryptAssRic...");
        java.lang.String _decryptAssRic_assric = "";
        java.lang.String _decryptAssRic__return = port.decryptAssRic(_decryptAssRic_assric);
        System.out.println("decryptAssRic.result=" + _decryptAssRic__return);


        }
        {
        System.out.println("Invoking encryptCodAssOld...");
        java.lang.String _encryptCodAssOld_codass = "";
        java.lang.String _encryptCodAssOld__return = port.encryptCodAssOld(_encryptCodAssOld_codass);
        System.out.println("encryptCodAssOld.result=" + _encryptCodAssOld__return);


        }
        {
        System.out.println("Invoking encryptCodAss...");
        java.lang.String _encryptCodAss_codass = "";
        java.lang.String _encryptCodAss__return = port.encryptCodAss(_encryptCodAss_codass);
        System.out.println("encryptCodAss.result=" + _encryptCodAss__return);


        }
        {
        System.out.println("Invoking decryptCodAss...");
        java.lang.String _decryptCodAss_codass = "";
        java.lang.String _decryptCodAss__return = port.decryptCodAss(_decryptCodAss_codass);
        System.out.println("decryptCodAss.result=" + _decryptCodAss__return);


        }
        {
        System.out.println("Invoking decryptXML...");
        java.math.BigDecimal _decryptXML_idXML = new java.math.BigDecimal("0");
        it.csi.apisan.apisanpresc.soap.sar.brokerservice.XmlType _decryptXML_type = null;
        java.lang.String _decryptXML_enkey = "";
        java.lang.String _decryptXML__return = port.decryptXML(_decryptXML_idXML, _decryptXML_type, _decryptXML_enkey);
        System.out.println("decryptXML.result=" + _decryptXML__return);


        }
        {
        System.out.println("Invoking serviceInfo...");
        java.lang.String _serviceInfo_user = "";
        java.lang.String _serviceInfo_pwd = "";
        java.lang.String _serviceInfo__return = port.serviceInfo(_serviceInfo_user, _serviceInfo_pwd);
        System.out.println("serviceInfo.result=" + _serviceInfo__return);


        }
        {
        System.out.println("Invoking encryptCodAssSac...");
        java.lang.String _encryptCodAssSac_codass = "";
        java.lang.String _encryptCodAssSac__return = port.encryptCodAssSac(_encryptCodAssSac_codass);
        System.out.println("encryptCodAssSac.result=" + _encryptCodAssSac__return);


        }
        {
        System.out.println("Invoking saveRicXML...");
        java.math.BigDecimal _saveRicXML_idXML = new java.math.BigDecimal("0");
        java.lang.String _saveRicXML_enkey = "";
        java.lang.String _saveRicXML_xml = "";
        boolean _saveRicXML_saveUtil = false;
        port.saveRicXML(_saveRicXML_idXML, _saveRicXML_enkey, _saveRicXML_xml, _saveRicXML_saveUtil);


        }
        {
        System.out.println("Invoking test...");
        java.lang.String _test__return = port.test();
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking cache...");
        it.csi.apisan.apisanpresc.soap.sar.brokerservice.CacheOperation _cache_operation = null;
        java.lang.String _cache_key = "";
        java.lang.String _cache__return = port.cache(_cache_operation, _cache_key);
        System.out.println("cache.result=" + _cache__return);


        }
        {
        System.out.println("Invoking dbInfo...");
        java.lang.String _dbInfo__return = port.dbInfo();
        System.out.println("dbInfo.result=" + _dbInfo__return);


        }
        {
        System.out.println("Invoking encryptAssRic...");
        java.lang.String _encryptAssRic_assric = "";
        java.lang.String _encryptAssRic__return = port.encryptAssRic(_encryptAssRic_assric);
        System.out.println("encryptAssRic.result=" + _encryptAssRic__return);


        }

        System.exit(0);
    }

}
