/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.082+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Crea_Appuntamento_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class CreaAppuntamentoWEBFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.CreaAppuntamentoWEBFault creaAppuntamentoWEBFault;

    public CreaAppuntamentoWEBFaultException() {
        super();
    }
    
    public CreaAppuntamentoWEBFaultException(String message) {
        super(message);
    }
    
    public CreaAppuntamentoWEBFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public CreaAppuntamentoWEBFaultException(String message, it.csi.screenserviziwebsol.CreaAppuntamentoWEBFault creaAppuntamentoWEBFault) {
        super(message);
        this.creaAppuntamentoWEBFault = creaAppuntamentoWEBFault;
    }

    public CreaAppuntamentoWEBFaultException(String message, it.csi.screenserviziwebsol.CreaAppuntamentoWEBFault creaAppuntamentoWEBFault, Throwable cause) {
        super(message, cause);
        this.creaAppuntamentoWEBFault = creaAppuntamentoWEBFault;
    }

    public it.csi.screenserviziwebsol.CreaAppuntamentoWEBFault getFaultInfo() {
        return this.creaAppuntamentoWEBFault;
    }
}
