/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.976+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Get_Appuntamenti_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetAppuntamentiWEBFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.GetAppuntamentiWEBFault getAppuntamentiWEBFault;

    public GetAppuntamentiWEBFault_Exception() {
        super();
    }
    
    public GetAppuntamentiWEBFault_Exception(String message) {
        super(message);
    }
    
    public GetAppuntamentiWEBFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAppuntamentiWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetAppuntamentiWEBFault getAppuntamentiWEBFault) {
        super(message);
        this.getAppuntamentiWEBFault = getAppuntamentiWEBFault;
    }

    public GetAppuntamentiWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetAppuntamentiWEBFault getAppuntamentiWEBFault, Throwable cause) {
        super(message, cause);
        this.getAppuntamentiWEBFault = getAppuntamentiWEBFault;
    }

    public it.csi.screenserviziwebsol.GetAppuntamentiWEBFault getFaultInfo() {
        return this.getAppuntamentiWEBFault;
    }
}
