/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.952+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Get_Dettaglio_Strutture_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetDettaglioStruttureWEBFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault;

    public GetDettaglioStruttureWEBFault_Exception() {
        super();
    }
    
    public GetDettaglioStruttureWEBFault_Exception(String message) {
        super(message);
    }
    
    public GetDettaglioStruttureWEBFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDettaglioStruttureWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault) {
        super(message);
        this.getDettaglioStruttureWEBFault = getDettaglioStruttureWEBFault;
    }

    public GetDettaglioStruttureWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault, Throwable cause) {
        super(message, cause);
        this.getDettaglioStruttureWEBFault = getDettaglioStruttureWEBFault;
    }

    public it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getFaultInfo() {
        return this.getDettaglioStruttureWEBFault;
    }
}
