/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.998+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Get_Date_Disponibili_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetDateDisponibiliWEBFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault;

    public GetDateDisponibiliWEBFault_Exception() {
        super();
    }
    
    public GetDateDisponibiliWEBFault_Exception(String message) {
        super(message);
    }
    
    public GetDateDisponibiliWEBFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDateDisponibiliWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault) {
        super(message);
        this.getDateDisponibiliWEBFault = getDateDisponibiliWEBFault;
    }

    public GetDateDisponibiliWEBFault_Exception(String message, it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault, Throwable cause) {
        super(message, cause);
        this.getDateDisponibiliWEBFault = getDateDisponibiliWEBFault;
    }

    public it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getFaultInfo() {
        return this.getDateDisponibiliWEBFault;
    }
}
