/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.015+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Get_Dettaglio_Strutture_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetDettaglioStruttureWEBFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault;

    public GetDettaglioStruttureWEBFaultException() {
        super();
    }
    
    public GetDettaglioStruttureWEBFaultException(String message) {
        super(message);
    }
    
    public GetDettaglioStruttureWEBFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDettaglioStruttureWEBFaultException(String message, it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault) {
        super(message);
        this.getDettaglioStruttureWEBFault = getDettaglioStruttureWEBFault;
    }

    public GetDettaglioStruttureWEBFaultException(String message, it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getDettaglioStruttureWEBFault, Throwable cause) {
        super(message, cause);
        this.getDettaglioStruttureWEBFault = getDettaglioStruttureWEBFault;
    }

    public it.csi.screenserviziwebsol.GetDettaglioStruttureWEBFault getFaultInfo() {
        return this.getDettaglioStruttureWEBFault;
    }
}
