/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.094+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Get_Date_Disponibili_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetDateDisponibiliWEBFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault;

    public GetDateDisponibiliWEBFaultException() {
        super();
    }
    
    public GetDateDisponibiliWEBFaultException(String message) {
        super(message);
    }
    
    public GetDateDisponibiliWEBFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDateDisponibiliWEBFaultException(String message, it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault) {
        super(message);
        this.getDateDisponibiliWEBFault = getDateDisponibiliWEBFault;
    }

    public GetDateDisponibiliWEBFaultException(String message, it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getDateDisponibiliWEBFault, Throwable cause) {
        super(message, cause);
        this.getDateDisponibiliWEBFault = getDateDisponibiliWEBFault;
    }

    public it.csi.screenserviziwebsol.GetDateDisponibiliWEBFault getFaultInfo() {
        return this.getDateDisponibiliWEBFault;
    }
}
