/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.086+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "GetDettaglioDocumentoDigitaleFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetDettaglioDocumentoDigitaleFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleFault getDettaglioDocumentoDigitaleFault;

    public GetDettaglioDocumentoDigitaleFaultException() {
        super();
    }
    
    public GetDettaglioDocumentoDigitaleFaultException(String message) {
        super(message);
    }
    
    public GetDettaglioDocumentoDigitaleFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDettaglioDocumentoDigitaleFaultException(String message, it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleFault getDettaglioDocumentoDigitaleFault) {
        super(message);
        this.getDettaglioDocumentoDigitaleFault = getDettaglioDocumentoDigitaleFault;
    }

    public GetDettaglioDocumentoDigitaleFaultException(String message, it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleFault getDettaglioDocumentoDigitaleFault, Throwable cause) {
        super(message, cause);
        this.getDettaglioDocumentoDigitaleFault = getDettaglioDocumentoDigitaleFault;
    }

    public it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleFault getFaultInfo() {
        return this.getDettaglioDocumentoDigitaleFault;
    }
}
