/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.956+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "GetElencoDocumentiDigitaliFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GetElencoDocumentiDigitaliFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliFault getElencoDocumentiDigitaliFault;

    public GetElencoDocumentiDigitaliFault_Exception() {
        super();
    }
    
    public GetElencoDocumentiDigitaliFault_Exception(String message) {
        super(message);
    }
    
    public GetElencoDocumentiDigitaliFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetElencoDocumentiDigitaliFault_Exception(String message, it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliFault getElencoDocumentiDigitaliFault) {
        super(message);
        this.getElencoDocumentiDigitaliFault = getElencoDocumentiDigitaliFault;
    }

    public GetElencoDocumentiDigitaliFault_Exception(String message, it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliFault getElencoDocumentiDigitaliFault, Throwable cause) {
        super(message, cause);
        this.getElencoDocumentiDigitaliFault = getElencoDocumentiDigitaliFault;
    }

    public it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliFault getFaultInfo() {
        return this.getElencoDocumentiDigitaliFault;
    }
}
