/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.055+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "GET_STRUTTURE_WEB2Fault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GETSTRUTTUREWEB2FaultException extends Exception {
    
    private it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault;

    public GETSTRUTTUREWEB2FaultException() {
        super();
    }
    
    public GETSTRUTTUREWEB2FaultException(String message) {
        super(message);
    }
    
    public GETSTRUTTUREWEB2FaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public GETSTRUTTUREWEB2FaultException(String message, it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault) {
        super(message);
        this.getSTRUTTUREWEB2Fault = getSTRUTTUREWEB2Fault;
    }

    public GETSTRUTTUREWEB2FaultException(String message, it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault, Throwable cause) {
        super(message, cause);
        this.getSTRUTTUREWEB2Fault = getSTRUTTUREWEB2Fault;
    }

    public it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getFaultInfo() {
        return this.getSTRUTTUREWEB2Fault;
    }
}
