/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.987+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "GET_STRUTTURE_WEB2Fault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class GETSTRUTTUREWEB2Fault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault;

    public GETSTRUTTUREWEB2Fault_Exception() {
        super();
    }
    
    public GETSTRUTTUREWEB2Fault_Exception(String message) {
        super(message);
    }
    
    public GETSTRUTTUREWEB2Fault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GETSTRUTTUREWEB2Fault_Exception(String message, it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault) {
        super(message);
        this.getSTRUTTUREWEB2Fault = getSTRUTTUREWEB2Fault;
    }

    public GETSTRUTTUREWEB2Fault_Exception(String message, it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getSTRUTTUREWEB2Fault, Throwable cause) {
        super(message, cause);
        this.getSTRUTTUREWEB2Fault = getSTRUTTUREWEB2Fault;
    }

    public it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Fault getFaultInfo() {
        return this.getSTRUTTUREWEB2Fault;
    }
}
