/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.039+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Scr_Ana_01Fault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class ScrAna01FaultException extends Exception {
    
    private it.csi.screenserviziwebsol.ScrAna01Fault scrAna01Fault;

    public ScrAna01FaultException() {
        super();
    }
    
    public ScrAna01FaultException(String message) {
        super(message);
    }
    
    public ScrAna01FaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public ScrAna01FaultException(String message, it.csi.screenserviziwebsol.ScrAna01Fault scrAna01Fault) {
        super(message);
        this.scrAna01Fault = scrAna01Fault;
    }

    public ScrAna01FaultException(String message, it.csi.screenserviziwebsol.ScrAna01Fault scrAna01Fault, Throwable cause) {
        super(message, cause);
        this.scrAna01Fault = scrAna01Fault;
    }

    public it.csi.screenserviziwebsol.ScrAna01Fault getFaultInfo() {
        return this.scrAna01Fault;
    }
}
