/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:52.005+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Scr_App_01Fault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class ScrApp01Fault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.ScrApp01Fault scrApp01Fault;

    public ScrApp01Fault_Exception() {
        super();
    }
    
    public ScrApp01Fault_Exception(String message) {
        super(message);
    }
    
    public ScrApp01Fault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ScrApp01Fault_Exception(String message, it.csi.screenserviziwebsol.ScrApp01Fault scrApp01Fault) {
        super(message);
        this.scrApp01Fault = scrApp01Fault;
    }

    public ScrApp01Fault_Exception(String message, it.csi.screenserviziwebsol.ScrApp01Fault scrApp01Fault, Throwable cause) {
        super(message, cause);
        this.scrApp01Fault = scrApp01Fault;
    }

    public it.csi.screenserviziwebsol.ScrApp01Fault getFaultInfo() {
        return this.scrApp01Fault;
    }
}
