/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.screenserviziwebsol;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:52.039+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ScreenServiziWebSOL", 
                  wsdlLocation = "file:/C:/Users/GIUSEP~1.MAR/AppData/Local/Temp/tempdir7145401218705132628.tmp/ScreenServiziWeb_SOL_1.wsdl",
                  targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/") 
public class ScreenServiziWebSOL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/ScreenServiziWebSOL/", "ScreenServiziWebSOL");
    public final static QName ScreenServiziWebSOLSOAP = new QName("http://www.csi.it/ScreenServiziWebSOL/", "ScreenServiziWebSOLSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/GIUSEP~1.MAR/AppData/Local/Temp/tempdir7145401218705132628.tmp/ScreenServiziWeb_SOL_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScreenServiziWebSOL_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/GIUSEP~1.MAR/AppData/Local/Temp/tempdir7145401218705132628.tmp/ScreenServiziWeb_SOL_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScreenServiziWebSOL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScreenServiziWebSOL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScreenServiziWebSOL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreenServiziWebSOL_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreenServiziWebSOL_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ScreenServiziWebSOL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ScreenServiziWebSOL
     */
    @WebEndpoint(name = "ScreenServiziWebSOLSOAP")
    public ScreenServiziWebSOL getScreenServiziWebSOLSOAP() {
        return super.getPort(ScreenServiziWebSOLSOAP, ScreenServiziWebSOL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScreenServiziWebSOL
     */
    @WebEndpoint(name = "ScreenServiziWebSOLSOAP")
    public ScreenServiziWebSOL getScreenServiziWebSOLSOAP(WebServiceFeature... features) {
        return super.getPort(ScreenServiziWebSOLSOAP, ScreenServiziWebSOL.class, features);
    }

}
