/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.screenserviziwebsol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.108+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", name = "ScreenServiziWebSOL")
@XmlSeeAlso({it.csi.gestoperatore.ObjectFactory.class, it.csi.gestutility.ObjectFactory.class, ObjectFactory.class, it.csi.gestcommon.ObjectFactory.class})
public interface ScreenServiziWebSOL {

    @WebMethod(operationName = "Scr_Cit_01", action = "http://www.csi.it/ScreenServiziWebSOL/Scr_Cit_01")
    @RequestWrapper(localName = "Scr_Cit_01", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrCit01")
    @ResponseWrapper(localName = "Scr_Cit_01Response", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrCit01Response")
    public void scrCit01(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Scr_Cit_01InParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.ScrCit01InParametersType scrCit01InParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Scr_Cit_01OutParameters", targetNamespace = "")
        javax.xml.ws.Holder<ScrCit01OutParametersType> scrCit01OutParameters
    ) throws ScrCit01FaultException;

    @WebMethod(operationName = "Get_Dettaglio_Strutture_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Get_Dettaglio_Strutture_WEB")
    @RequestWrapper(localName = "Get_Dettaglio_Strutture_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDettaglioStruttureWEB")
    @ResponseWrapper(localName = "Get_Dettaglio_Strutture_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDettaglioStruttureWEBResponse")
    public void getDettaglioStruttureWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Get_Dettaglio_Strutture_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GetDettaglioStruttureWEBInParametersType getDettaglioStruttureWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Get_Dettaglio_Strutture_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<GetDettaglioStruttureWEBOutParametersType> getDettaglioStruttureWEBOutParameters
    ) throws GetDettaglioStruttureWEBFaultException;

    @WebMethod(operationName = "GetElencoDocumentiDigitali", action = "http://www.csi.it/ScreenServiziWebSOL/GetElencoDocumentiDigitali")
    @RequestWrapper(localName = "GetElencoDocumentiDigitali", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetElencoDocumentiDigitali")
    @ResponseWrapper(localName = "GetElencoDocumentiDigitaliResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliResponse")
    public void getElencoDocumentiDigitali(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "GetElencoDocumentiDigitaliInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GetElencoDocumentiDigitaliInParametersType getElencoDocumentiDigitaliInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetElencoDocumentiDigitaliOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<ArrayOfGetElencoDocumentiDigitaliOutParametersType> getElencoDocumentiDigitaliOutParameters
    ) throws GetElencoDocumentiDigitaliFaultException;

    @WebMethod(operationName = "Set_Situazione_Ass_Ind_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Set_Situazione_Ass_Ind_WEB")
    @RequestWrapper(localName = "Set_Situazione_Ass_Ind_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.SetSituazioneAssIndWEB")
    @ResponseWrapper(localName = "Set_Situazione_Ass_Ind_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.SetSituazioneAssIndWEBResponse")
    public void setSituazioneAssIndWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Set_Situazione_Ass_Ind_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.SetSituazioneAssIndWEBInParametersType setSituazioneAssIndWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Set_Situazione_Ass_Ind_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<SetSituazioneAssIndWEBOutParametersType> setSituazioneAssIndWEBOutParameters
    ) throws SetSituazioneAssIndWEBFaultException;

    @WebMethod(operationName = "Scr_Mam_01", action = "http://www.csi.it/ScreenServiziWebSOL/Scr_Mam_01")
    @RequestWrapper(localName = "Scr_Mam_01", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrMam01")
    @ResponseWrapper(localName = "Scr_Mam_01Response", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrMam01Response")
    public void scrMam01(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Scr_Mam_01InParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.ScrMam01InParametersType scrMam01InParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Scr_Mam_01OutParameters", targetNamespace = "")
        javax.xml.ws.Holder<ScrMam01OutParametersType> scrMam01OutParameters
    ) throws ScrMam01FaultException;

    @WebMethod(operationName = "Scr_Ana_01", action = "http://www.csi.it/ScreenServiziWebSOL/Scr_Ana_01")
    @RequestWrapper(localName = "Scr_Ana_01", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrAna01")
    @ResponseWrapper(localName = "Scr_Ana_01Response", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrAna01Response")
    public void scrAna01(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Scr_Ana_01InParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.ScrAna01InParametersType scrAna01InParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Scr_Ana_01OutParameters", targetNamespace = "")
        javax.xml.ws.Holder<ScrAna01OutParametersType> scrAna01OutParameters
    ) throws ScrAna01FaultException;

    @WebMethod(operationName = "Get_Appuntamenti_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Get_Appuntamenti_WEB")
    @RequestWrapper(localName = "Get_Appuntamenti_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetAppuntamentiWEB")
    @ResponseWrapper(localName = "Get_Appuntamenti_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetAppuntamentiWEBResponse")
    public void getAppuntamentiWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Get_Appuntamenti_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GetAppuntamentiWEBInParametersType getAppuntamentiWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Get_Appuntamenti_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<GetAppuntamentiWEBOutParametersType> getAppuntamentiWEBOutParameters
    ) throws GetAppuntamentiWEBFaultException;

    @WebMethod(operationName = "VerificaAssistita", action = "http://www.csi.it/ScreenServiziWebSOL/VerificaAssistita")
    @RequestWrapper(localName = "VerificaAssistita", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.VerificaAssistita")
    @ResponseWrapper(localName = "VerificaAssistitaResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.VerificaAssistitaResponse")
    public void verificaAssistita(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "VerificaAssistitaOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<VerificaAssistitaOutParametersType> verificaAssistitaOutParameters
    ) throws VerificaAssistitaFaultException;

    @WebMethod(operationName = "GET_STRUTTURE_WEB2", action = "http://www.csi.it/ScreenServiziWebSOL/GET_STRUTTURE_WEB2")
    @RequestWrapper(localName = "GET_STRUTTURE_WEB2", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GETSTRUTTUREWEB2")
    @ResponseWrapper(localName = "GET_STRUTTURE_WEB2Response", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GETSTRUTTUREWEB2Response")
    public void getSTRUTTUREWEB2(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "GET_STRUTTURE_WEB2InParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GETSTRUTTUREWEB2InParametersType getSTRUTTUREWEB2InParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "GET_STRUTTURE_WEB2OutParameters", targetNamespace = "")
        javax.xml.ws.Holder<GETSTRUTTUREWEB2OutParametersType> getSTRUTTUREWEB2OutParameters
    ) throws GETSTRUTTUREWEB2FaultException;

    @WebMethod(operationName = "Set_Situazione_Ass_Tel_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Set_Situazione_Ass_Tel_WEB")
    @RequestWrapper(localName = "Set_Situazione_Ass_Tel_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.SetSituazioneAssTelWEB")
    @ResponseWrapper(localName = "Set_Situazione_Ass_Tel_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.SetSituazioneAssTelWEBResponse")
    public void setSituazioneAssTelWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Set_Situazione_Ass_Tel_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.SetSituazioneAssTelWEBInParametersType setSituazioneAssTelWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Set_Situazione_Ass_Tel_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<SetSituazioneAssTelWEBOutParametersType> setSituazioneAssTelWEBOutParameters
    ) throws SetSituazioneAssTelWEBFaultException;

    @WebMethod(operationName = "TrasmettiNotifica", action = "http://www.csi.it/ScreenServiziWebSOL/TrasmettiNotifica")
    @RequestWrapper(localName = "TrasmettiNotifica", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.TrasmettiNotifica")
    @ResponseWrapper(localName = "TrasmettiNotificaResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.TrasmettiNotificaResponse")
    @WebResult(name = "errori", targetNamespace = "")
    public it.csi.gestutility.ErroriType trasmettiNotifica(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "TrasmettiNotificaInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.TrasmettiNotificaInParametersType trasmettiNotificaInParameters
    ) throws TrasmettiNotificaFaultException;

    @WebMethod(operationName = "Crea_Appuntamento_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Crea_Appuntamento_WEB")
    @RequestWrapper(localName = "Crea_Appuntamento_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.CreaAppuntamentoWEB")
    @ResponseWrapper(localName = "Crea_Appuntamento_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.CreaAppuntamentoWEBResponse")
    public void creaAppuntamentoWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Crea_Appuntamento_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.CreaAppuntamentoWEBInParametersType creaAppuntamentoWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Crea_Appuntamento_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<CreaAppuntamentoWEBOutParametersType> creaAppuntamentoWEBOutParameters
    ) throws CreaAppuntamentoWEBFaultException;

    @WebMethod(operationName = "GetDettaglioDocumentoDigitale", action = "http://www.csi.it/ScreenServiziWebSOL/GetDettaglioDocumentoDigitale")
    @RequestWrapper(localName = "GetDettaglioDocumentoDigitale", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitale")
    @ResponseWrapper(localName = "GetDettaglioDocumentoDigitaleResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleResponse")
    public void getDettaglioDocumentoDigitale(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "GetDettaglioDocumentoDigitaleInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GetDettaglioDocumentoDigitaleInParametersType getDettaglioDocumentoDigitaleInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDettaglioDocumentoDigitaleOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<GetDettaglioDocumentoDigitaleOutParametersType> getDettaglioDocumentoDigitaleOutParameters
    ) throws GetDettaglioDocumentoDigitaleFaultException;

    @WebMethod(operationName = "Get_Date_Disponibili_WEB", action = "http://www.csi.it/ScreenServiziWebSOL/Get_Date_Disponibili_WEB")
    @RequestWrapper(localName = "Get_Date_Disponibili_WEB", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDateDisponibiliWEB")
    @ResponseWrapper(localName = "Get_Date_Disponibili_WEBResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.GetDateDisponibiliWEBResponse")
    public void getDateDisponibiliWEB(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Get_Date_Disponibili_WEBInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.GetDateDisponibiliWEBInParametersType getDateDisponibiliWEBInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Get_Date_Disponibili_WEBOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<GetDateDisponibiliWEBOutParametersType> getDateDisponibiliWEBOutParameters
    ) throws GetDateDisponibiliWEBFaultException;

    @WebMethod(operationName = "Check_Eta_Screening", action = "http://www.csi.it/ScreenServiziWebSOL/Check_Eta_Screening")
    @RequestWrapper(localName = "Check_Eta_Screening", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.CheckEtaScreening")
    @ResponseWrapper(localName = "Check_Eta_ScreeningResponse", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.CheckEtaScreeningResponse")
    public void checkEtaScreening(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Check_Eta_ScreeningInParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.CheckEtaScreeningInParametersType checkEtaScreeningInParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Check_Eta_ScreeningOutParameters", targetNamespace = "")
        javax.xml.ws.Holder<CheckEtaScreeningOutParametersType> checkEtaScreeningOutParameters
    ) throws CheckEtaScreeningFaultException;

    @WebMethod(operationName = "Scr_App_01", action = "http://www.csi.it/ScreenServiziWebSOL/Scr_App_01")
    @RequestWrapper(localName = "Scr_App_01", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrApp01")
    @ResponseWrapper(localName = "Scr_App_01Response", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/", className = "it.csi.screenserviziwebsol.ScrApp01Response")
    public void scrApp01(
        @WebParam(name = "Credenziali", targetNamespace = "")
        it.csi.screenserviziwebsol.CredenzialiType credenziali,
        @WebParam(name = "Scr_App_01InParameters", targetNamespace = "")
        it.csi.screenserviziwebsol.ScrApp01InParametersType scrApp01InParameters,
        @WebParam(mode = WebParam.Mode.OUT, name = "Errori", targetNamespace = "")
        javax.xml.ws.Holder<it.csi.gestutility.ErroriType> errori,
        @WebParam(mode = WebParam.Mode.OUT, name = "Scr_App_01OutParameters", targetNamespace = "")
        javax.xml.ws.Holder<ScrApp01OutParametersType> scrApp01OutParameters
    ) throws ScrApp01FaultException;
}
