/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.983+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Set_Situazione_Ass_Tel_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class SetSituazioneAssTelWEBFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault;

    public SetSituazioneAssTelWEBFault_Exception() {
        super();
    }
    
    public SetSituazioneAssTelWEBFault_Exception(String message) {
        super(message);
    }
    
    public SetSituazioneAssTelWEBFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SetSituazioneAssTelWEBFault_Exception(String message, it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault) {
        super(message);
        this.setSituazioneAssTelWEBFault = setSituazioneAssTelWEBFault;
    }

    public SetSituazioneAssTelWEBFault_Exception(String message, it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault, Throwable cause) {
        super(message, cause);
        this.setSituazioneAssTelWEBFault = setSituazioneAssTelWEBFault;
    }

    public it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault getFaultInfo() {
        return this.setSituazioneAssTelWEBFault;
    }
}
