/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.060+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Set_Situazione_Ass_Tel_WEBFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class SetSituazioneAssTelWEBFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault;

    public SetSituazioneAssTelWEBFaultException() {
        super();
    }
    
    public SetSituazioneAssTelWEBFaultException(String message) {
        super(message);
    }
    
    public SetSituazioneAssTelWEBFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetSituazioneAssTelWEBFaultException(String message, it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault) {
        super(message);
        this.setSituazioneAssTelWEBFault = setSituazioneAssTelWEBFault;
    }

    public SetSituazioneAssTelWEBFaultException(String message, it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault setSituazioneAssTelWEBFault, Throwable cause) {
        super(message, cause);
        this.setSituazioneAssTelWEBFault = setSituazioneAssTelWEBFault;
    }

    public it.csi.screenserviziwebsol.SetSituazioneAssTelWEBFault getFaultInfo() {
        return this.setSituazioneAssTelWEBFault;
    }
}
