/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-03-24T11:59:49.050+01:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "VerificaAssistitaFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class VerificaAssistitaFaultException extends Exception {
    
    private it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault;

    public VerificaAssistitaFaultException() {
        super();
    }
    
    public VerificaAssistitaFaultException(String message) {
        super(message);
    }
    
    public VerificaAssistitaFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public VerificaAssistitaFaultException(String message, it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault) {
        super(message);
        this.verificaAssistitaFault = verificaAssistitaFault;
    }

    public VerificaAssistitaFaultException(String message, it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault, Throwable cause) {
        super(message, cause);
        this.verificaAssistitaFault = verificaAssistitaFault;
    }

    public it.csi.screenserviziwebsol.VerificaAssistitaFault getFaultInfo() {
        return this.verificaAssistitaFault;
    }
}
