/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.screenserviziwebsol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2020-06-26T15:12:51.979+02:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "VerificaAssistitaFault", targetNamespace = "http://www.csi.it/ScreenServiziWebSOL/")
public class VerificaAssistitaFault_Exception extends Exception {
    
    private it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault;

    public VerificaAssistitaFault_Exception() {
        super();
    }
    
    public VerificaAssistitaFault_Exception(String message) {
        super(message);
    }
    
    public VerificaAssistitaFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public VerificaAssistitaFault_Exception(String message, it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault) {
        super(message);
        this.verificaAssistitaFault = verificaAssistitaFault;
    }

    public VerificaAssistitaFault_Exception(String message, it.csi.screenserviziwebsol.VerificaAssistitaFault verificaAssistitaFault, Throwable cause) {
        super(message, cause);
        this.verificaAssistitaFault = verificaAssistitaFault;
    }

    public it.csi.screenserviziwebsol.VerificaAssistitaFault getFaultInfo() {
        return this.verificaAssistitaFault;
    }
}
