/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.gpr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-09-28T16:08:01.287+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://csi.it", name = "proxyGPRPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProxyGPRPortType {

    @WebMethod(operationName = "EstrazioneListaTicketMetadatiGPR", action = "http://csi.it/EstrazioneListaTicketMetadatiGPR")
    @Action(input = "http://csi.it/EstrazioneListaTicketMetadatiGPR", output = "http://csi.it/ptbSoap/EstrazioneListaTicketMetadatiGPRResponse")
    @RequestWrapper(localName = "EstrazioneListaTicketMetadatiGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.EstrazioneListaTicketMetadatiGPR")
    @ResponseWrapper(localName = "EstrazioneListaTicketMetadatiGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.EstrazioneListaTicketMetadatiGPRResponse")
    @WebResult(name = "ERRORE", targetNamespace = "http://csi.it")
    public it.csi.gpr.Errore estrazioneListaTicketMetadatiGPR(
        @WebParam(name = "ASR", targetNamespace = "http://csi.it")
        java.lang.String asr,
        @WebParam(name = "UUID", targetNamespace = "http://csi.it")
        java.lang.String uuid,
        @WebParam(name = "AZIONE", targetNamespace = "http://csi.it")
        java.lang.String azione
    );

    @WebMethod(operationName = "GetModalitaErogazioneAmmissibiliGPR", action = "http://csi.it/GetModalitaErogazioneAmmissibiliGPR")
    @Action(input = "http://csi.it/GetModalitaErogazioneAmmissibiliGPR", output = "http://csi.it/ptbSoap/GetModalitaErogazioneAmmissibiliGPRResponse")
    @RequestWrapper(localName = "GetModalitaErogazioneAmmissibiliGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetModalitaErogazioneAmmissibiliGPR")
    @ResponseWrapper(localName = "GetModalitaErogazioneAmmissibiliGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetModalitaErogazioneAmmissibiliGPRResponse")
    @WebResult(name = "risposta", targetNamespace = "http://csi.it")
    public it.csi.gpr.ModalitaErogazioneAmmissibiliGPRResultType getModalitaErogazioneAmmissibiliGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.GetModalitaErogazioneAmmissibiliGPRRequest richiesta
    );

    @WebMethod(operationName = "DispacciaFlussoRendicontazione", action = "http://csi.it/DispacciaFlussoRendicontazione")
    @Action(input = "http://csi.it/DispacciaFlussoRendicontazione", output = "http://csi.it/ptbSoap/DispacciaFlussoRendicontazioneResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "DispacciaFlussoRendicontazioneResponse", targetNamespace = "http://csi.it", partName = "parameters")
    public DispacciaFlussoRendicontazioneResponse dispacciaFlussoRendicontazione(
        @WebParam(partName = "parameters", name = "DispacciaFlussoRendicontazioneRequest", targetNamespace = "http://csi.it")
        DispacciaFlussoRendicontazioneRequest parameters
    );

    @WebMethod(operationName = "SetCodiceVersamentoGPR", action = "http://csi.it/SetCodiceVersamentoGPR")
    @Action(input = "http://csi.it/SetCodiceVersamentoGPR", output = "http://csi.it/ptbSoap/SetCodiceVersamentoGPRResponse")
    @RequestWrapper(localName = "SetCodiceVersamentoGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetCodiceVersamentoGPR")
    @ResponseWrapper(localName = "SetCodiceVersamentoGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetCodiceVersamentoGPRResponse")
    @WebResult(name = "SetCodiceVersamentoGPRResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.SetCodiceVersamentoGPRResponseType setCodiceVersamentoGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.RichiestaSetCodiceVersamento richiesta
    );

    @WebMethod(operationName = "GetConfigLottoIUVGPR", action = "http://csi.it/GetConfigLottoIUVGPR")
    @Action(input = "http://csi.it/GetConfigLottoIUVGPR", output = "http://csi.it/ptbSoap/GetConfigLottoIUVGPRResponse")
    @RequestWrapper(localName = "GetConfigLottoIUVGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetConfigLottoIUVGPR")
    @ResponseWrapper(localName = "GetConfigLottoIUVGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetConfigLottoIUVGPRResponse")
    public void getConfigLottoIUVGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.RichiestaGetConfigLottoIUV richiesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "risposta", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<RispostaGetConfigLottoIUVGPRResponse> risposta,
        @WebParam(mode = WebParam.Mode.OUT, name = "ERRORE", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<Errore> errore
    );

    @WebMethod(operationName = "GetSingleIuvGPR", action = "http://csi.it/GetSingleIuvGPR")
    @Action(input = "http://csi.it/GetSingleIuvGPR", output = "http://csi.it/ptbSoap/GetSingleIuvGPRResponse")
    @RequestWrapper(localName = "GetSingleIuvGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetSingleIuvGPR")
    @ResponseWrapper(localName = "GetSingleIuvGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetSingleIuvGPRResponse")
    public void getSingleIuvGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.RichiestaIuv richiesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "risposta", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<RispostaIuv> risposta,
        @WebParam(mode = WebParam.Mode.OUT, name = "ERRORE", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<Errore> errore
    );

    @WebMethod(operationName = "GetAvvisiUNPGPR", action = "http://csi.it/GetAvvisiUNPGPR")
    @Action(input = "http://csi.it/GetAvvisiUNPGPR", output = "http://csi.it/ptbSoap/GetAvvisiUNPGPRResponse")
    @RequestWrapper(localName = "GetAvvisiUNPGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetAvvisiUNPGPR")
    @ResponseWrapper(localName = "GprListaAvvisiUNP", targetNamespace = "http://csi.it", className = "it.csi.gpr.GprListaAvvisiUNP")
    @WebResult(name = "AVVISO", targetNamespace = "http://csi.it")
    public java.util.List<it.csi.gpr.Avviso> getAvvisiUNPGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.AvvisoRequest richiesta
    );

    @WebMethod(operationName = "AttivazioneRecuperoMetadati", action = "http://csi.it/AttivazioneRecuperoMetadati")
    @Action(input = "http://csi.it/AttivazioneRecuperoMetadati", output = "http://csi.it/ptbSoap/AttivazioneRecuperoMetadatiResponse")
    @RequestWrapper(localName = "AttivazioneRecuperoMetadati", targetNamespace = "http://csi.it", className = "it.csi.gpr.AttivazioneRecuperoMetadati")
    @ResponseWrapper(localName = "AttivazioneRecuperoMetadatiResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.AttivazioneRecuperoMetadatiResponse")
    @WebResult(name = "AttivazioneRecuperoMetadatiResult", targetNamespace = "http://csi.it")
    public java.lang.String attivazioneRecuperoMetadati(
        @WebParam(name = "ASR", targetNamespace = "http://csi.it")
        java.lang.String asr,
        @WebParam(name = "DATA_RECUPERO_DA", targetNamespace = "http://csi.it")
        java.lang.String dataRECUPERODA,
        @WebParam(name = "DATA_RECUPERO_A", targetNamespace = "http://csi.it")
        java.lang.String dataRECUPEROA
    );

    @WebMethod(operationName = "SetOpposizionePrecompilazione730GPR", action = "http://csi.it/SetOpposizionePrecompilazione730GPR")
    @Action(input = "http://csi.it/SetOpposizionePrecompilazione730GPR", output = "http://csi.it/ptbSoap/SetOpposizionePrecompilazione730GPRResponse")
    @RequestWrapper(localName = "SetOpposizionePrecompilazione730GPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetOpposizionePrecompilazione730GPR")
    @ResponseWrapper(localName = "SetOpposizionePrecompilazione730GPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetOpposizionePrecompilazione730GPRResponse")
    @WebResult(name = "SetOpposizionePrecompilazione730GPRResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.SetOpposizionePrecompilazione730GPRResultType setOpposizionePrecompilazione730GPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.SetOpposizionePrecompilazione730GPRRequest richiesta
    );

    @WebMethod(operationName = "GetListaTicketCF", action = "http://csi.it/GetListaTicketCF")
    @Action(input = "http://csi.it/GetListaTicketCF", output = "http://csi.it/ptbSoap/GetListaTicketCFResponse")
    @RequestWrapper(localName = "GetListaTicketCF", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetListaTicketCF")
    @ResponseWrapper(localName = "GetListaTicketCFResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetListaTicketCFResponse")
    @WebResult(name = "GetListaTicketCFResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.Importi getListaTicketCF(
        @WebParam(name = "ASR", targetNamespace = "http://csi.it")
        java.lang.String asr,
        @WebParam(name = "UUID", targetNamespace = "http://csi.it")
        java.lang.String uuid,
        @WebParam(name = "AZIONE", targetNamespace = "http://csi.it")
        java.lang.String azione,
        @WebParam(name = "NUMERO_SPORTELLO", targetNamespace = "http://csi.it")
        java.lang.String numeroSPORTELLO,
        @WebParam(name = "NUMERO_PRATICA", targetNamespace = "http://csi.it")
        java.lang.String numeroPRATICA,
        @WebParam(name = "CODICE_FISCALE", targetNamespace = "http://csi.it")
        java.lang.String codiceFISCALE,
        @WebParam(name = "IMPORTO_PRATICA", targetNamespace = "http://csi.it")
        java.lang.String importoPRATICA
    );

    @WebMethod(operationName = "SetAvvenutoPagamento", action = "http://csi.it/SetAvvenutoPagamento")
    @Action(input = "http://csi.it/SetAvvenutoPagamento", output = "http://csi.it/ptbSoap/SetAvvenutoPagamentoResponse")
    @RequestWrapper(localName = "SetAvvenutoPagamento", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetAvvenutoPagamento")
    @ResponseWrapper(localName = "SetAvvenutoPagamentoResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetAvvenutoPagamentoResponse")
    @WebResult(name = "SetAvvenutoPagamentoResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.Quietanza setAvvenutoPagamento(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.Pagamento richiesta
    );

    @WebMethod(operationName = "SetModalitaErogazioneRimborsoGPR", action = "http://csi.it/SetModalitaErogazioneRimborsoGPR")
    @Action(input = "http://csi.it/SetModalitaErogazioneRimborsoGPR", output = "http://csi.it/ptbSoap/SetModalitaErogazioneRimborsoGPRResponse")
    @RequestWrapper(localName = "SetModalitaErogazioneRimborsoGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetModalitaErogazioneRimborsoGPR")
    @ResponseWrapper(localName = "SetModalitaErogazioneRimborsoGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetModalitaErogazioneRimborsoGPRResponse")
    @WebResult(name = "SetModalitaErogazioneRimborsoGPRResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.SetModalitaErogazioneRimborsoGPRResultType setModalitaErogazioneRimborsoGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.SetModalitaErogazioneRimborsoGPRRequest richiesta
    );

    @WebMethod(operationName = "GetImportoTicket", action = "http://csi.it/GetImportoTicket")
    @Action(input = "http://csi.it/GetImportoTicket", output = "http://csi.it/ptbSoap/GetImportoTicketResponse")
    @RequestWrapper(localName = "GetImportoTicket", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetImportoTicket")
    @ResponseWrapper(localName = "GetImportoTicketResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetImportoTicketResponse")
    @WebResult(name = "GetImportoTicketResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.Importi getImportoTicket(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.Richiesta richiesta
    );

    @WebMethod(operationName = "LMSGetTicketPagati", action = "http://csi.it/LMSGetTicketPagati")
    @Action(input = "http://csi.it/LMSGetTicketPagati", output = "http://csi.it/ptbSoap/LMSGetTicketPagatiResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LMSGetTicketPagatiResponse", targetNamespace = "http://csi.it", partName = "parameters")
    public LMSGetTicketPagatiResponse lmsGetTicketPagati(
        @WebParam(partName = "parameters", name = "LMSGetTicketPagatiRequest", targetNamespace = "http://csi.it")
        LMSGetTicketPagatiRequest parameters
    );

    @WebMethod(operationName = "GetMultiIUVGPR", action = "http://csi.it/GetMultiIUVGPR")
    @Action(input = "http://csi.it/GetMultiIUVGPR", output = "http://csi.it/ptbSoap/GetMultiIUVGPRResponse")
    @RequestWrapper(localName = "GetMultiIUVGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetMultiIUVGPR")
    @ResponseWrapper(localName = "GetMultiIUVGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetMultiIUVGPRResponse")
    public void getMultiIUVGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.RichiestaMultiIuv richiesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetMultiIUVGPRResult", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<RispostaMultiIuv> getMultiIUVGPRResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ERRORE", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<Errore> errore
    );

    @WebMethod(operationName = "GetListaRimborsiGPR", action = "http://csi.it/GetListaRimborsiGPR")
    @Action(input = "http://csi.it/GetListaRimborsiGPR", output = "http://csi.it/ptbSoap/GetListaRimborsiGPRResponse")
    @RequestWrapper(localName = "GetListaRimborsiGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetListaRimborsiGPR")
    @ResponseWrapper(localName = "GetListaRimborsiGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetListaRimborsiGPRResponse")
    @WebResult(name = "GetListaRimborsiGPRResult", targetNamespace = "http://csi.it")
    public it.csi.gpr.ListaRimborsiGPRResultType getListaRimborsiGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.GetListaRimborsiGPRRequest richiesta
    );

    @WebMethod(operationName = "SetAssociazioneIUVTicketGPR", action = "http://csi.it/SetAssociazioneIUVTicketGPR")
    @Action(input = "http://csi.it/SetAssociazioneIUVTicketGPR", output = "http://csi.it/ptbSoap/SetAssociazioneIUVTicketGPRResponse")
    @RequestWrapper(localName = "SetAssociazioneIUVTicketGPR", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetAssociazioneIUVTicketGPR")
    @ResponseWrapper(localName = "SetAssociazioneIUVTicketGPRResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.SetAssociazioneIUVTicketGPRResponse")
    public void setAssociazioneIUVTicketGPR(
        @WebParam(name = "richiesta", targetNamespace = "http://csi.it")
        it.csi.gpr.RichiestaAssociazioneIUVTicket richiesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "risposta", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<RispostaAssociazioneIUVTicket> risposta,
        @WebParam(mode = WebParam.Mode.OUT, name = "ERRORE", targetNamespace = "http://csi.it")
        javax.xml.ws.Holder<Errore> errore
    );

    @WebMethod(operationName = "Echo", action = "http://csi.it/Echo")
    @Action(input = "http://csi.it/Echo", output = "http://csi.it/ptbSoap/EchoResponse")
    @RequestWrapper(localName = "Echo", targetNamespace = "http://csi.it", className = "it.csi.gpr.Echo")
    @ResponseWrapper(localName = "EchoResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.EchoResponse")
    @WebResult(name = "EchoResult", targetNamespace = "http://csi.it")
    public java.lang.String echo(
        @WebParam(name = "arg", targetNamespace = "http://csi.it")
        java.lang.String arg
    );

    @WebMethod(operationName = "GetDatiSensibiliUtenteCentrale", action = "http://csi.it/GetDatiSensibiliUtenteCentrale")
    @Action(input = "http://csi.it/GetDatiSensibiliUtenteCentrale", output = "http://csi.it/ptbSoap/GetDatiSensibiliUtenteCentraleResponse")
    @RequestWrapper(localName = "GetDatiSensibiliUtenteCentrale", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetDatiSensibiliUtenteCentrale")
    @ResponseWrapper(localName = "GetDatiSensibiliUtenteCentraleResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.GetDatiSensibiliUtenteCentraleResponse")
    @WebResult(name = "GetDatiSensibiliUtenteCentraleResult", targetNamespace = "http://csi.it")
    public java.lang.String getDatiSensibiliUtenteCentrale(
        @WebParam(name = "ASR", targetNamespace = "http://csi.it")
        java.lang.String asr,
        @WebParam(name = "UUID", targetNamespace = "http://csi.it")
        java.lang.String uuid,
        @WebParam(name = "AZIONE", targetNamespace = "http://csi.it")
        java.lang.String azione,
        @WebParam(name = "NUMERO_PRATICA", targetNamespace = "http://csi.it")
        java.lang.String numeroPRATICA
    );

    @WebMethod(operationName = "AttivazioneAcquisizioneListaStatoTicket", action = "http://csi.it/AttivazioneAcquisizioneListaStatoTicket")
    @Action(input = "http://csi.it/AttivazioneAcquisizioneListaStatoTicket", output = "http://csi.it/ptbSoap/AttivazioneAcquisizioneListaStatoTicketResponse")
    @RequestWrapper(localName = "AttivazioneAcquisizioneListaStatoTicket", targetNamespace = "http://csi.it", className = "it.csi.gpr.AttivazioneAcquisizioneListaStatoTicket")
    @ResponseWrapper(localName = "AttivazioneAcquisizioneListaStatoTicketResponse", targetNamespace = "http://csi.it", className = "it.csi.gpr.AttivazioneAcquisizioneListaStatoTicketResponse")
    @WebResult(name = "AttivazioneAcquisizioneListaStatoTicketResult", targetNamespace = "http://csi.it")
    public java.lang.String attivazioneAcquisizioneListaStatoTicket(
        @WebParam(name = "AZIONE", targetNamespace = "http://csi.it")
        java.lang.String azione,
        @WebParam(name = "ASR", targetNamespace = "http://csi.it")
        java.lang.String asr
    );

    @WebMethod(operationName = "LMSGetRicevuta", action = "http://csi.it/LMSGetRicevuta")
    @Action(input = "http://csi.it/LMSGetRicevuta", output = "http://csi.it/ptbSoap/LMSGetRicevutaResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LMSGetRicevutaResponse", targetNamespace = "http://csi.it", partName = "parameters")
    public LMSGetRicevutaResponse lmsGetRicevuta(
        @WebParam(partName = "parameters", name = "LMSGetRicevutaRequest", targetNamespace = "http://csi.it")
        LMSGetRicevutaRequest parameters
    );
}
