/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.iccws.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-12-13T11:29:32.746+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "FarmaciaService")
@XmlSeeAlso({ObjectFactory.class, it.csi.iccws.dma.ObjectFactory.class, it.csi.iccws.dmaccbl.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FarmaciaService {

    @WebMethod(action = "http://dmaccbl.csi.it/getFarmacieAderenti")
    @WebResult(name = "getFarmacieAderentiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getFarmacieAderentiResponse")
    public GetFarmacieAderentiResponse getFarmacieAderenti(
        @WebParam(partName = "getFarmacieAderentiRequest", name = "getFarmacieAderentiRequest", targetNamespace = "http://dmaccbl.csi.it/")
        GetFarmacieAderentiRequest getFarmacieAderentiRequest
    );

    @WebMethod(action = "http://dmaccbl.csi.it/verificaFarmacista")
    @WebResult(name = "verificaFarmacistaResponse", targetNamespace = "http://dmacc.csi.it/", partName = "verificaFarmacistaResponse")
    public VerificaFarmacistaResponse verificaFarmacista(
        @WebParam(partName = "verificaFarmacistaRequest", name = "verificaFarmacistaRequest", targetNamespace = "http://dmaccbl.csi.it/")
        VerificaFarmacistaRequest verificaFarmacistaRequest
    );
}
