/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.iccws.dmacc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-12-13T11:29:32.798+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "FarmaciaService", 
                  wsdlLocation = "file:/D:/subversion/dma/farmab/trunk/docs/lccews_FarmaciaService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class FarmaciaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "FarmaciaService");
    public final static QName FarmaciaService = new QName("http://dmacc.csi.it/", "FarmaciaService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/subversion/dma/farmab/trunk/docs/lccews_FarmaciaService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FarmaciaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/subversion/dma/farmab/trunk/docs/lccews_FarmaciaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FarmaciaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FarmaciaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FarmaciaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FarmaciaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FarmaciaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FarmaciaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FarmaciaService
     */
    @WebEndpoint(name = "FarmaciaService")
    public FarmaciaService getFarmaciaService() {
        return super.getPort(FarmaciaService, FarmaciaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FarmaciaService
     */
    @WebEndpoint(name = "FarmaciaService")
    public FarmaciaService getFarmaciaService(WebServiceFeature... features) {
        return super.getPort(FarmaciaService, FarmaciaService.class, features);
    }

}
