/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.scaricostudi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2018-10-18T17:13:01.831+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "CCScaricoStudiService", 
                  wsdlLocation = "https://tst-feapi-dma.isan.csi.it:443/dmaccmed/services/CCScaricoStudiService.CCScaricoStudiServiceHttpSoap12Endpoint?wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class CCScaricoStudiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "CCScaricoStudiService");
    public final static QName CCScaricoStudiServiceHttpsEndpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpsEndpoint");
    public final static QName CCScaricoStudiServiceHttpsSoap11Endpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpsSoap11Endpoint");
    public final static QName CCScaricoStudiServiceHttpSoap11Endpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpSoap11Endpoint");
    public final static QName CCScaricoStudiServiceHttpEndpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpEndpoint");
    public final static QName CCScaricoStudiServiceHttpSoap12Endpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpSoap12Endpoint");
    public final static QName CCScaricoStudiServiceHttpsSoap12Endpoint = new QName("http://dmacc.csi.it/", "CCScaricoStudiServiceHttpsSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-feapi-dma.isan.csi.it:443/dmaccmed/services/CCScaricoStudiService.CCScaricoStudiServiceHttpSoap12Endpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CCScaricoStudiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://tst-feapi-dma.isan.csi.it:443/dmaccmed/services/CCScaricoStudiService.CCScaricoStudiServiceHttpSoap12Endpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CCScaricoStudiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCScaricoStudiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCScaricoStudiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricoStudiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricoStudiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricoStudiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsEndpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsEndpoint() {
        return super.getPort(CCScaricoStudiServiceHttpsEndpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsEndpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpsEndpoint, CCScaricoStudiServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsSoap11Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsSoap11Endpoint() {
        return super.getPort(CCScaricoStudiServiceHttpsSoap11Endpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsSoap11Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpsSoap11Endpoint, CCScaricoStudiServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpSoap11Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpSoap11Endpoint() {
        return super.getPort(CCScaricoStudiServiceHttpSoap11Endpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpSoap11Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpSoap11Endpoint, CCScaricoStudiServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpEndpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpEndpoint() {
        return super.getPort(CCScaricoStudiServiceHttpEndpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpEndpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpEndpoint, CCScaricoStudiServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpSoap12Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpSoap12Endpoint() {
        return super.getPort(CCScaricoStudiServiceHttpSoap12Endpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpSoap12Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpSoap12Endpoint, CCScaricoStudiServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsSoap12Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsSoap12Endpoint() {
        return super.getPort(CCScaricoStudiServiceHttpsSoap12Endpoint, CCScaricoStudiServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricoStudiServicePortType
     */
    @WebEndpoint(name = "CCScaricoStudiServiceHttpsSoap12Endpoint")
    public CCScaricoStudiServicePortType getCCScaricoStudiServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CCScaricoStudiServiceHttpsSoap12Endpoint, CCScaricoStudiServicePortType.class, features);
    }

}
