/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisancons.integration.conspref.consprefbe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsensoBeService", targetNamespace = "http://consprefbe.csi.it/", wsdlLocation = "http://localhost:10110/consprefbe-web/ConsensoBeService?wsdl")
public class ConsensoBeService_Service
    extends Service
{

    private final static URL CONSENSOBESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSENSOBESERVICE_EXCEPTION;
    private final static QName CONSENSOBESERVICE_QNAME = new QName("http://consprefbe.csi.it/", "ConsensoBeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10110/consprefbe-web/ConsensoBeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSENSOBESERVICE_WSDL_LOCATION = url;
        CONSENSOBESERVICE_EXCEPTION = e;
    }

    public ConsensoBeService_Service() {
        super(__getWsdlLocation(), CONSENSOBESERVICE_QNAME);
    }

    public ConsensoBeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSENSOBESERVICE_QNAME, features);
    }

    public ConsensoBeService_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSENSOBESERVICE_QNAME);
    }

    public ConsensoBeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSENSOBESERVICE_QNAME, features);
    }

    public ConsensoBeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsensoBeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsensoBeService
     */
    @WebEndpoint(name = "ConsensoBeServiceImplPort")
    public ConsensoBeService getConsensoBeServiceImplPort() {
        return super.getPort(new QName("http://consprefbe.csi.it/", "ConsensoBeServiceImplPort"), ConsensoBeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsensoBeService
     */
    @WebEndpoint(name = "ConsensoBeServiceImplPort")
    public ConsensoBeService getConsensoBeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://consprefbe.csi.it/", "ConsensoBeServiceImplPort"), ConsensoBeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSENSOBESERVICE_EXCEPTION!= null) {
            throw CONSENSOBESERVICE_EXCEPTION;
        }
        return CONSENSOBESERVICE_WSDL_LOCATION;
    }

}
