/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisancons.integration.conspref.consprefbe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsensoBeService", targetNamespace = "http://consprefbe.csi.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	it.csi.apisan.apisancons.integration.conspref.consprefbe.ObjectFactory.class,
	it.csi.apisan.apisancons.integration.conspref.consensocittadino.ObjectFactory.class,
	it.csi.apisan.apisancons.integration.conspref.errorecittadino.ObjectFactory.class,
	it.csi.apisan.apisancons.integration.conspref.fontecittadino.ObjectFactory.class
})
public interface ConsensoBeService {


    /**
     * 
     * @param consultaStatoBeRequest
     * @return
     *     returns it.csi.consprefbe.ConsultaStatoBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaStatoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaStatoBeResponse")
    public ConsultaStatoBeResponse consultaStatoBeService(
        @WebParam(name = "consultaStatoBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaStatoBeRequest")
        ConsultaCodificaBe consultaStatoBeRequest);

    /**
     * 
     * @param inserisciConsensoBeRequest
     * @return
     *     returns it.csi.consprefbe.InserisciConsensoBeResponse
     */
    @WebMethod
    @WebResult(name = "inserisciConsensoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "inserisciConsensoBeResponse")
    public InserisciConsensoBeResponse inserisciConsensoBeService(
        @WebParam(name = "inserisciConsensoBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "inserisciConsensoBeRequest")
        InserisciConsensoBe inserisciConsensoBeRequest);

    /**
     * 
     * @param consultaInformativa
     * @return
     *     returns it.csi.consprefbe.ConsultaInformativaResponse
     */
    @WebMethod
    @WebResult(name = "consultaInformativaResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaInformativaResponse")
    public ConsultaInformativaResponse consultaInformativaBeService(
        @WebParam(name = "consultaInformativa", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaInformativa")
        ConsultaInformativa consultaInformativa);

    /**
     * 
     * @param consultaAsrBeRequest
     * @return
     *     returns it.csi.consprefbe.ConsultaAsrBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaAsrBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaAsrBeResponse")
    public ConsultaAsrBeResponse consultaAsrBeService(
        @WebParam(name = "consultaAsrBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaAsrBeRequest")
        ConsultaCodificaBe consultaAsrBeRequest);

    /**
     * 
     * @param consultaConsensoBe
     * @return
     *     returns it.csi.consprefbe.ConsultaConsensoBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaConsensoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaConsensoBeResponse")
    public ConsultaConsensoBeResponse consultaConsensoBeService(
        @WebParam(name = "consultaConsensoBe", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaConsensoBe")
        ConsultaConsensoBe consultaConsensoBe);

    /**
     * 
     * @param modificaConsensoBeRequest
     * @return
     *     returns it.csi.consprefbe.ModificaConsensoBeResponse
     */
    @WebMethod
    @WebResult(name = "modificaConsensoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "modificaConsensoBeResponse")
    public ModificaConsensoBeResponse modificaConsensoBeService(
        @WebParam(name = "modificaConsensoBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "modificaConsensoBeRequest")
        ModificaConsensoBe modificaConsensoBeRequest);

    /**
     * 
     * @param consultaTipoBeRequest
     * @return
     *     returns it.csi.consprefbe.ConsultaTipoBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaTipoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaTipoBeResponse")
    public ConsultaTipoBeResponse consultaTipoBeService(
        @WebParam(name = "consultaTipoBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaTipoBeRequest")
        ConsultaCodificaBe consultaTipoBeRequest);

    
    /**
     * 
     * @param ConsultaNotificheBe
     * @return
     *     returns it.csi.consprefbe.ConsultaNotificheBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaNotificheBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaNotificheBeResponse")
    public ConsultaNotificheBeResponse consultaNotificheBeService(
        @WebParam(partName = "consultaNotificheBe", name = "consultaNotificheBe", targetNamespace = "http://consprefbe.csi.it/")
        ConsultaNotificheBe consultaNotificheBe);
    
    
    
    
    /**
     * 
     * @param consultaSottoTipoBeRequest
     * @return
     *     returns it.csi.consprefbe.ConsultaSottoTipoBeResponse
     */
    @WebMethod
    @WebResult(name = "consultaSottoTipoBeResponse", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaSottoTipoBeResponse")
    public ConsultaSottoTipoBeResponse consultaSottoTipoBeService(
        @WebParam(name = "consultaSottoTipoBeRequest", targetNamespace = "http://consprefbe.csi.it/", partName = "consultaSottoTipoBeRequest")
        ConsultaCodificaBe consultaSottoTipoBeRequest);

}
