/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.oscuramento.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-25T09:39:49.729+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "OscuramentoService")
@XmlSeeAlso({it.csi.apisan.apisanfse.integration.oscuramento.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OscuramentoService {

    @WebMethod
    @WebResult(name = "setOscuramentoResponse", targetNamespace = "http://dmacc.csi.it/", partName = "setOscuramentoResponse")
    public SetOscuramentoResponse setOscuramento(
        @WebParam(partName = "setOscuramento", name = "setOscuramento", targetNamespace = "http://dmacc.csi.it/")
        SetOscuramento setOscuramento
    );
}
