/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanfse.integration.oscuramento.dmacc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-25T09:39:49.690+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class OscuramentoService_OscuramentoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "OscuramentoService");

    private OscuramentoService_OscuramentoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OscuramentoService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OscuramentoService_Service ss = new OscuramentoService_Service(wsdlURL, SERVICE_NAME);
        OscuramentoService port = ss.getOscuramentoServicePort();  
        
        {
        System.out.println("Invoking setOscuramento...");
        it.csi.apisan.apisanfse.integration.oscuramento.dmacc.SetOscuramento _setOscuramento_setOscuramento = null;
        it.csi.apisan.apisanfse.integration.oscuramento.dmacc.SetOscuramentoResponse _setOscuramento__return = port.setOscuramento(_setOscuramento_setOscuramento);
        System.out.println("setOscuramento.result=" + _setOscuramento__return);


        }

        System.exit(0);
    }

}
