/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanpresc.soap.dma.elencoricetteservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-11-14T14:35:50.224+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class CCElencoRicetteStampaPromemoriaService_CCElencoRicetteStampaPromemoriaServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "CCElencoRicetteStampaPromemoriaService");

    private CCElencoRicetteStampaPromemoriaService_CCElencoRicetteStampaPromemoriaServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CCElencoRicetteStampaPromemoriaService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CCElencoRicetteStampaPromemoriaService_Service ss = new CCElencoRicetteStampaPromemoriaService_Service(wsdlURL, SERVICE_NAME);
        CCElencoRicetteStampaPromemoriaService port = ss.getCCElencoRicetteStampaPromemoriaServicePort();  
        
        {
        System.out.println("Invoking elencoRicetteStampaPromemoria...");
        it.csi.apisan.apisanpresc.soap.dma.elencoricetteservice.ElencoRicetteStampaPromemoriaRequest _elencoRicetteStampaPromemoria_elencoRicetteStampaPromemoriaRequest = new it.csi.apisan.apisanpresc.soap.dma.elencoricetteservice.ElencoRicetteStampaPromemoriaRequest();
        it.csi.apisan.apisanpresc.soap.dma.elencoricetteservice.ElencoRicetteStampaPromemoriaResponse _elencoRicetteStampaPromemoria__return = port.elencoRicetteStampaPromemoria(_elencoRicetteStampaPromemoria_elencoRicetteStampaPromemoriaRequest);
        System.out.println("elencoRicetteStampaPromemoria.result=" + _elencoRicetteStampaPromemoria__return);


        }

        System.exit(0);
    }

}
