/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.dma.farmab.interfacews.msg.setdisassociadevice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2022-01-03T10:39:14.527+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class SetDisassociaDeviceService_SetDisassociaDevicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", "SetDisassociaDeviceServiceImplService");

    private SetDisassociaDeviceService_SetDisassociaDevicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SetDisassociaDeviceServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SetDisassociaDeviceServiceImplService ss = new SetDisassociaDeviceServiceImplService(wsdlURL, SERVICE_NAME);
        SetDisassociaDeviceService port = ss.getSetDisassociaDevicePort();  
        
        {
        System.out.println("Invoking setDisassociaDevice...");
        it.csi.dma.farmab.interfacews.msg.setdisassociadevice.Richiedente _setDisassociaDevice_richiedente = null;
        java.lang.String _setDisassociaDevice_cfCittadino = "";
        javax.xml.ws.Holder<java.lang.String> _setDisassociaDevice_esito = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.setdisassociadevice.ElencoErroriType> _setDisassociaDevice_elencoErrori = new javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.setdisassociadevice.ElencoErroriType>();
        port.setDisassociaDevice(_setDisassociaDevice_richiedente, _setDisassociaDevice_cfCittadino, _setDisassociaDevice_esito, _setDisassociaDevice_elencoErrori);

        System.out.println("setDisassociaDevice._setDisassociaDevice_esito=" + _setDisassociaDevice_esito.value);
        System.out.println("setDisassociaDevice._setDisassociaDevice_elencoErrori=" + _setDisassociaDevice_elencoErrori.value);

        }

        System.exit(0);
    }

}
