/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.dma.farmab.interfacews.msg.setdisassociadevice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2022-01-03T10:39:14.578+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", name = "SetDisassociaDeviceService")
@XmlSeeAlso({ObjectFactory.class})
public interface SetDisassociaDeviceService {

    @WebMethod
    @RequestWrapper(localName = "setDisassociaDevice", targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", className = "it.csi.dma.farmab.interfacews.msg.setdisassociadevice.SetDisassociaDeviceRequest")
    @ResponseWrapper(localName = "setDisassociaDeviceResponse", targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/", className = "it.csi.dma.farmab.interfacews.msg.setdisassociadevice.SetDisassociaDeviceResponse")
    public void setDisassociaDevice(
        @WebParam(name = "richiedente", targetNamespace = "http://setdisassociadevice.msg.interfacews.farmab.dma.csi.it/")
        it.csi.dma.farmab.interfacews.msg.setdisassociadevice.Richiedente richiedente,
        @WebParam(name = "cfCittadino", targetNamespace = "")
        java.lang.String cfCittadino,
        @WebParam(mode = WebParam.Mode.OUT, name = "esito", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> esito,
        @WebParam(mode = WebParam.Mode.OUT, name = "elencoErrori", targetNamespace = "")
        javax.xml.ws.Holder<ElencoErroriType> elencoErrori
    );
}
