/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanfse.integration.consensoini.dmacc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-03-20T12:03:28.810+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class CCConsensoINIExtServicePortType_CCConsensoINIExtServiceHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "CCConsensoINIExtService");

    private CCConsensoINIExtServicePortType_CCConsensoINIExtServiceHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CCConsensoINIExtService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CCConsensoINIExtService ss = new CCConsensoINIExtService(wsdlURL, SERVICE_NAME);
        CCConsensoINIExtServicePortType port = ss.getCCConsensoINIExtServiceHttpEndpoint();  
        
        {
        System.out.println("Invoking statoConsensi...");
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.StatoConsensiExtRequeste _statoConsensi_statoConsensi = null;
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.StatoConsensiResponse _statoConsensi__return = port.statoConsensi(_statoConsensi_statoConsensi);
        System.out.println("statoConsensi.result=" + _statoConsensi__return);


        }
        {
        System.out.println("Invoking comunicazioneConsensi...");
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.ComunicazioneConsensiExtRequeste _comunicazioneConsensi_comunicazioneConsensi = null;
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.ComunicazioneConsensiResponse _comunicazioneConsensi__return = port.comunicazioneConsensi(_comunicazioneConsensi_comunicazioneConsensi);
        System.out.println("comunicazioneConsensi.result=" + _comunicazioneConsensi__return);


        }
        {
        System.out.println("Invoking recuperoInformativa...");
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.RecuperoInformativaExtRequeste _recuperoInformativa_recuperoInformativa = null;
        it.csi.apisan.apisanfse.integration.consensoini.dmacc.RecuperoInformativaResponse _recuperoInformativa__return = port.recuperoInformativa(_recuperoInformativa_recuperoInformativa);
        System.out.println("recuperoInformativa.result=" + _recuperoInformativa__return);


        }

        System.exit(0);
    }

}
