/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.consensoini.dmacc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-03-20T12:03:28.851+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "CCConsensoINIExtService", 
                  wsdlLocation = "https://tst-feapi-dma.isan.csi.it/dmaccmedrti/services/CCConsensoINIExtService?wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class CCConsensoINIExtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "CCConsensoINIExtService");
    public final static QName CCConsensoINIExtServiceHttpsSoap11Endpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpsSoap11Endpoint");
    public final static QName CCConsensoINIExtServiceHttpSoap11Endpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpSoap11Endpoint");
    public final static QName CCConsensoINIExtServiceHttpsEndpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpsEndpoint");
    public final static QName CCConsensoINIExtServiceHttpEndpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpEndpoint");
    public final static QName CCConsensoINIExtServiceHttpsSoap12Endpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpsSoap12Endpoint");
    public final static QName CCConsensoINIExtServiceHttpSoap12Endpoint = new QName("http://dmacc.csi.it/", "CCConsensoINIExtServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-feapi-dma.isan.csi.it/dmaccmedrti/services/CCConsensoINIExtService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CCConsensoINIExtService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://tst-feapi-dma.isan.csi.it/dmaccmedrti/services/CCConsensoINIExtService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CCConsensoINIExtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCConsensoINIExtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCConsensoINIExtService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCConsensoINIExtService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCConsensoINIExtService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCConsensoINIExtService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsSoap11Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsSoap11Endpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpsSoap11Endpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsSoap11Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpsSoap11Endpoint, CCConsensoINIExtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpSoap11Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpSoap11Endpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpSoap11Endpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpSoap11Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpSoap11Endpoint, CCConsensoINIExtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsEndpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsEndpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpsEndpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsEndpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpsEndpoint, CCConsensoINIExtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpEndpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpEndpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpEndpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpEndpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpEndpoint, CCConsensoINIExtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsSoap12Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsSoap12Endpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpsSoap12Endpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpsSoap12Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpsSoap12Endpoint, CCConsensoINIExtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpSoap12Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpSoap12Endpoint() {
        return super.getPort(CCConsensoINIExtServiceHttpSoap12Endpoint, CCConsensoINIExtServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCConsensoINIExtServicePortType
     */
    @WebEndpoint(name = "CCConsensoINIExtServiceHttpSoap12Endpoint")
    public CCConsensoINIExtServicePortType getCCConsensoINIExtServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CCConsensoINIExtServiceHttpSoap12Endpoint, CCConsensoINIExtServicePortType.class, features);
    }

}
