/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanpresc.soap.dma.scaricapdfricetta;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.apisan.apisanpresc.common.ApiSanPrescConstants;

import java.net.URL;
import java.net.MalformedURLException;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-09-17T14:49:45.297+02:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CCScaricaPDFRicettaService",
                  wsdlLocation = "https://tst-be-dma.isan.csi.it/dmaccpromed/services/CCScaricaPDFRicettaService?wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class CCScaricaPdfRicettaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "CCScaricaPdfRicettaService");
    public final static QName CCScaricaPdfRicettaServicePort = new QName("http://dmacc.csi.it/", "CCScaricaPdfRicettaServicePort");
    static {
        URL url = null;
        try {
            url = new URL(ApiSanPrescConstants.DMA_PRO_STAMPARICETTAPDF_WSDL);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CCScaricaPdfRicettaService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tst-bejava-dma.isan.csi.it/dmaccproblrti/CCScaricaPdfRicettaService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CCScaricaPdfRicettaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCScaricaPdfRicettaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCScaricaPdfRicettaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricaPdfRicettaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricaPdfRicettaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCScaricaPdfRicettaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CCScaricaPdfRicettaService
     */
    @WebEndpoint(name = "CCScaricaPdfRicettaServicePort")
    public CCScaricaPdfRicettaService getCCScaricaPdfRicettaServicePort() {
        return super.getPort(CCScaricaPdfRicettaServicePort, CCScaricaPdfRicettaService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCScaricaPdfRicettaService
     */
    @WebEndpoint(name = "CCScaricaPdfRicettaServicePort")
    public CCScaricaPdfRicettaService getCCScaricaPdfRicettaServicePort(WebServiceFeature... features) {
        return super.getPort(CCScaricaPdfRicettaServicePort, CCScaricaPdfRicettaService.class, features);
    }

}
