/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanpresc.soap.dma.scaricapdfricetta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-11-15T09:59:07.656+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "CCScaricaPdfRicettaService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CCScaricaPdfRicettaService {

    @WebMethod
    @WebResult(name = "scaricaPdfRicettaResponse", targetNamespace = "http://dmacc.csi.it/", partName = "scaricaPdfRicettaResponse")
    public ScaricaPdfRicettaResponse scaricaPdfRicetta(
        @WebParam(partName = "scaricaPdfRicettaRequest", name = "scaricaPdfRicettaRequest", targetNamespace = "http://dmacc.csi.it/")
        ScaricaPdfRicettaRequest scaricaPdfRicettaRequest
    );
}
