/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanpresc.soap.sar.visprescsol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-10-10T11:36:59.081+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://visualizzaprescrittopazientesol.xsd.dem.regione.piemonte.it", name = "visualizzaPrescrittoPazienteSOLPT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VisualizzaPrescrittoPazienteSOLPT {

    @WebMethod(action = "http://visualizzaprescrittopazientesol.xsd.dem.regione.piemonte.it/VisualizzaPrescrittoPazienteSOL")
    @WebResult(name = "VisualizzaPrescrittoPazienteSOLRicevuta", targetNamespace = "http://visualizzaprescrittopazientesolricevuta.xsd.dem.regione.piemonte.it", partName = "VisualizzaPrescrittoPazienteSOLRicevuta")
    public VisualizzaPrescrittoPazienteSOLRicevuta visualizzaPrescrittoPazienteSOL(
        @WebParam(partName = "VisualizzaPrescrittoPazienteSOLRichiesta", name = "VisualizzaPrescrittoPazienteSOLRichiesta", targetNamespace = "http://visualizzaprescrittopazientesolrichiesta.xsd.dem.regione.piemonte.it")
        VisualizzaPrescrittoPazienteSOLRichiesta visualizzaPrescrittoPazienteSOLRichiesta
    );
}
