/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package org.wso2.ws.dataservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-05-14T08:42:59.464+02:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "DataServiceFault", targetNamespace = "http://ws.wso2.org/dataservice")
public class DataServiceFault extends Exception {
    
    private java.lang.String dataServiceFault;

    public DataServiceFault() {
        super();
    }
    
    public DataServiceFault(String message) {
        super(message);
    }
    
    public DataServiceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DataServiceFault(String message, java.lang.String dataServiceFault) {
        super(message);
        this.dataServiceFault = dataServiceFault;
    }

    public DataServiceFault(String message, java.lang.String dataServiceFault, Throwable cause) {
        super(message, cause);
        this.dataServiceFault = dataServiceFault;
    }

    public java.lang.String getFaultInfo() {
        return this.dataServiceFault;
    }
}
