/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package org.wso2.ws.dataservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-05-14T08:42:59.469+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "GPR_DATASERVICEPortType")
@XmlSeeAlso({it.csi.ObjectFactory.class, ObjectFactory.class})
public interface GPRDATASERVICEPortType {

    @WebMethod(operationName = "GprEstrazioneListaTicketMetadatiGPAupdate", action = "urn:GprEstrazioneListaTicketMetadatiGPAupdate")
    @Action(input = "urn:GprEstrazioneListaTicketMetadatiGPAupdate")
    @Oneway
    @RequestWrapper(localName = "GprEstrazioneListaTicketMetadatiGPAupdate", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEstrazioneListaTicketMetadatiGPAupdate")
    public void gprEstrazioneListaTicketMetadatiGPAupdate();

    @WebMethod(operationName = "GprEstrazioneListaTicketMetadatiGPAListaFatturaNested", action = "urn:GprEstrazioneListaTicketMetadatiGPAListaFatturaNested")
    @Action(input = "urn:GprEstrazioneListaTicketMetadatiGPAListaFatturaNested", output = "urn:GprEstrazioneListaTicketMetadatiGPAListaFatturaNestedResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEstrazioneListaTicketMetadatiGPAListaFatturaNestedDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LISTA_FATTURA", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public LISTAFATTURA gprEstrazioneListaTicketMetadatiGPAListaFatturaNested(
        @WebParam(partName = "parameters", name = "GprEstrazioneListaTicketMetadatiGPAListaFatturaNested", targetNamespace = "http://ws.wso2.org/dataservice")
        GprEstrazioneListaTicketMetadatiGPAListaFatturaNested parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEndpointPerAttivazioneRecuperoMetadati", action = "urn:GprEndpointPerAttivazioneRecuperoMetadati")
    @Action(input = "urn:GprEndpointPerAttivazioneRecuperoMetadati", output = "urn:GprEndpointPerAttivazioneRecuperoMetadatiResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerAttivazioneRecuperoMetadatiDataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerAttivazioneRecuperoMetadati", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerAttivazioneRecuperoMetadati")
    @ResponseWrapper(localName = "GprEndpointPerAttivazioneRecuperoMetadati", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerAttivazioneRecuperoMetadati")
    public void gprEndpointPerAttivazioneRecuperoMetadati(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ASR", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> asr
    ) throws DataServiceFault;

    @WebMethod(operationName = "LmsGetRicevutePagamentiOnoratiByPratica", action = "urn:LmsGetRicevutePagamentiOnoratiByPratica")
    @Action(input = "urn:LmsGetRicevutePagamentiOnoratiByPratica", output = "urn:LmsGetRicevutePagamentiOnoratiByPraticaResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:LmsGetRicevutePagamentiOnoratiByPraticaDataServiceFault")})
    @RequestWrapper(localName = "LmsGetRicevutePagamentiOnoratiByPratica", targetNamespace = "http://csi.it", className = "it.csi.LmsGetRicevutePagamentiOnoratiByPratica")
    @ResponseWrapper(localName = "elencoRicevutePagamentiOnorati", targetNamespace = "http://csi.it", className = "it.csi.ElencoRicevutePagamentiOnorati")
    @WebResult(name = "RICEVUTA_PAGAMENTO", targetNamespace = "http://csi.it")
    public java.util.List<it.csi.RICEVUTAPAGAMENTO> lmsGetRicevutePagamentiOnoratiByPratica(
        @WebParam(name = "id_prenotazione", targetNamespace = "http://csi.it")
        java.math.BigDecimal idPrenotazione
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEstrazioneListaTicketMetadatiGPA", action = "urn:GprEstrazioneListaTicketMetadatiGPA")
    @Action(input = "urn:GprEstrazioneListaTicketMetadatiGPA", output = "urn:GprEstrazioneListaTicketMetadatiGPAResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEstrazioneListaTicketMetadatiGPADataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "EstrazioneListaTicketMetadatiResult", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public EstrazioneListaTicketMetadatiResult gprEstrazioneListaTicketMetadatiGPA(
        @WebParam(partName = "parameters", name = "GprEstrazioneListaTicketMetadatiGPA", targetNamespace = "http://ws.wso2.org/dataservice")
        GprEstrazioneListaTicketMetadatiGPA parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEndpointPerGetListaFlussiFRDaInviareGPA", action = "urn:GprEndpointPerGetListaFlussiFRDaInviareGPA")
    @Action(input = "urn:GprEndpointPerGetListaFlussiFRDaInviareGPA", output = "urn:GprEndpointPerGetListaFlussiFRDaInviareGPAResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerGetListaFlussiFRDaInviareGPADataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerGetListaFlussiFRDaInviareGPA", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetListaFlussiFRDaInviareGPA")
    @ResponseWrapper(localName = "GprEndpointPerGetListaFlussiFRDaInviareGPAResult", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetListaFlussiFRDaInviareGPAResult")
    @WebResult(name = "FLUSSO", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.FLUSSO> gprEndpointPerGetListaFlussiFRDaInviareGPA() throws DataServiceFault;

    @WebMethod(operationName = "GprEndpointPerGetDatiSensibiliUtenteCentrale", action = "urn:GprEndpointPerGetDatiSensibiliUtenteCentrale")
    @Action(input = "urn:GprEndpointPerGetDatiSensibiliUtenteCentrale", output = "urn:GprEndpointPerGetDatiSensibiliUtenteCentraleResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerGetDatiSensibiliUtenteCentraleDataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerGetDatiSensibiliUtenteCentrale", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetDatiSensibiliUtenteCentrale")
    @ResponseWrapper(localName = "GprEndpointPerGetDatiSensibiliUtenteCentrale", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetDatiSensibiliUtenteCentrale")
    public void gprEndpointPerGetDatiSensibiliUtenteCentrale(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ASR", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> asr
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprGetConfigLottoIUV", action = "urn:GprGetConfigLottoIUV")
    @Action(input = "urn:GprGetConfigLottoIUV", output = "urn:GprGetConfigLottoIUVResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprGetConfigLottoIUVDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "risposta", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public Risposta gprGetConfigLottoIUV(
        @WebParam(partName = "parameters", name = "GprGetConfigLottoIUV", targetNamespace = "http://ws.wso2.org/dataservice")
        GprGetConfigLottoIUV parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "LmsGetTicketPagatiFunc", action = "urn:LmsGetTicketPagatiFunc")
    @Action(input = "urn:LmsGetTicketPagatiFunc", output = "urn:LmsGetTicketPagatiFuncResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:LmsGetTicketPagatiFuncDataServiceFault")})
    @RequestWrapper(localName = "LmsGetTicketPagatiFunc", targetNamespace = "http://csi.it", className = "it.csi.LmsGetTicketPagatiFunc")
    @ResponseWrapper(localName = "elencoTicketPagati", targetNamespace = "http://csi.it", className = "it.csi.ElencoTicketPagati")
    @WebResult(name = "PRATICA", targetNamespace = "http://csi.it")
    public java.util.List<it.csi.PRATICA> lmsGetTicketPagatiFunc(
        @WebParam(name = "codiceFiscale", targetNamespace = "http://csi.it")
        java.lang.String codiceFiscale,
        @WebParam(name = "codiceFiscaleDelgante", targetNamespace = "http://csi.it")
        java.lang.String codiceFiscaleDelgante,
        @WebParam(name = "annoPagamento", targetNamespace = "http://csi.it")
        java.lang.String annoPagamento
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprListaAvvisiUNP", action = "urn:GprListaAvvisiUNP")
    @Action(input = "urn:GprListaAvvisiUNP", output = "urn:GprListaAvvisiUNPResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprListaAvvisiUNPDataServiceFault")})
    @RequestWrapper(localName = "GprListaAvvisiUNP", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaAvvisiUNP")
    @ResponseWrapper(localName = "GprListaAvvisiUNP", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaAvvisiUNP")
    public void gprListaAvvisiUNP(
        @WebParam(mode = WebParam.Mode.INOUT, name = "cryptPwd", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> cryptPwd
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprListaDescrizioneStrutturaByNRE", action = "urn:GprListaDescrizioneStrutturaByNRE")
    @Action(input = "urn:GprListaDescrizioneStrutturaByNRE", output = "urn:GprListaDescrizioneStrutturaByNREResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprListaDescrizioneStrutturaByNREDataServiceFault")})
    @RequestWrapper(localName = "GprListaDescrizioneStrutturaByNRE", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaDescrizioneStrutturaByNRE")
    @ResponseWrapper(localName = "GprListaDescrizioneStrutturaByNREResult", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaDescrizioneStrutturaByNREResult")
    @WebResult(name = "NREDESCRIZIONE", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.NREDESCRIZIONE> gprListaDescrizioneStrutturaByNRE(
        @WebParam(name = "NRE", targetNamespace = "http://ws.wso2.org/dataservice")
        java.util.List<java.lang.String> nre
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprRecuperoListaTicketMetadatiUpdate", action = "urn:GprRecuperoListaTicketMetadatiUpdate")
    @Action(input = "urn:GprRecuperoListaTicketMetadatiUpdate")
    @Oneway
    @RequestWrapper(localName = "GprRecuperoListaTicketMetadatiUpdate", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprRecuperoListaTicketMetadatiUpdate")
    public void gprRecuperoListaTicketMetadatiUpdate(
        @WebParam(name = "DAL", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String dal,
        @WebParam(name = "AL", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String al
    );

    @WebMethod(operationName = "GprGetConfigLottoIUVCodiceAsrCodiceVersamento", action = "urn:GprGetConfigLottoIUVCodiceAsrCodiceVersamento")
    @Action(input = "urn:GprGetConfigLottoIUVCodiceAsrCodiceVersamento", output = "urn:GprGetConfigLottoIUVCodiceAsrCodiceVersamentoResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprGetConfigLottoIUVCodiceAsrCodiceVersamentoDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "risposta", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public Risposta gprGetConfigLottoIUVCodiceAsrCodiceVersamento(
        @WebParam(partName = "parameters", name = "GprGetConfigLottoIUVCodiceAsrCodiceVersamento", targetNamespace = "http://ws.wso2.org/dataservice")
        GprGetConfigLottoIUVCodiceAsrCodiceVersamento parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprListaRELByCF", action = "urn:GprListaRELByCF")
    @Action(input = "urn:GprListaRELByCF", output = "urn:GprListaRELByCFResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprListaRELByCFDataServiceFault")})
    @RequestWrapper(localName = "GprListaRELByCF", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaRELByCF")
    @ResponseWrapper(localName = "GprListaRELByCF", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprListaRELByCF")
    public void gprListaRELByCF(
        @WebParam(mode = WebParam.Mode.INOUT, name = "codice_fiscale", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> codiceFiscale
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprInsertLogMessage", action = "urn:GprInsertLogMessage")
    @Action(input = "urn:GprInsertLogMessage")
    @Oneway
    @RequestWrapper(localName = "GprInsertLogMessage", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprInsertLogMessage")
    public void gprInsertLogMessage(
        @WebParam(name = "id_asr", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String idAsr,
        @WebParam(name = "uuid", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String uuid,
        @WebParam(name = "cod_stato", targetNamespace = "http://ws.wso2.org/dataservice")
        java.math.BigDecimal codStato,
        @WebParam(name = "stringa_xml", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String stringaXml,
        @WebParam(name = "cod_servizio", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String codServizio,
        @WebParam(name = "azione", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String azione,
        @WebParam(name = "numero_sportello", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String numeroSportello,
        @WebParam(name = "numero_pratica", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String numeroPratica,
        @WebParam(name = "codice_fiscale", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String codiceFiscale,
        @WebParam(name = "uuid_ptb", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String uuidPtb
    );

    @WebMethod(operationName = "GprEndpointPerAttivazioneAcquisizioneListaStatoTicket", action = "urn:GprEndpointPerAttivazioneAcquisizioneListaStatoTicket")
    @Action(input = "urn:GprEndpointPerAttivazioneAcquisizioneListaStatoTicket", output = "urn:GprEndpointPerAttivazioneAcquisizioneListaStatoTicketResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerAttivazioneAcquisizioneListaStatoTicketDataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerAttivazioneAcquisizioneListaStatoTicket", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerAttivazioneAcquisizioneListaStatoTicket")
    @ResponseWrapper(localName = "GprEndpointPerAttivazioneAcquisizioneListaStatoTicket", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerAttivazioneAcquisizioneListaStatoTicket")
    public void gprEndpointPerAttivazioneAcquisizioneListaStatoTicket(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ASR", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> asr
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEndpointPerEstrazioneTicketMetadatiGPR", action = "urn:GprEndpointPerEstrazioneTicketMetadatiGPR")
    @Action(input = "urn:GprEndpointPerEstrazioneTicketMetadatiGPR", output = "urn:GprEndpointPerEstrazioneTicketMetadatiGPRResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerEstrazioneTicketMetadatiGPRDataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerEstrazioneTicketMetadatiGPR", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerEstrazioneTicketMetadatiGPR")
    @ResponseWrapper(localName = "GprEndpointPerEstrazioneTicketMetadatiGPR", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerEstrazioneTicketMetadatiGPR")
    public void gprEndpointPerEstrazioneTicketMetadatiGPR() throws DataServiceFault;

    @WebMethod(operationName = "GprGetConfigLottoIUVCodiceAsr", action = "urn:GprGetConfigLottoIUVCodiceAsr")
    @Action(input = "urn:GprGetConfigLottoIUVCodiceAsr", output = "urn:GprGetConfigLottoIUVCodiceAsrResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprGetConfigLottoIUVCodiceAsrDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "risposta", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public Risposta gprGetConfigLottoIUVCodiceAsr(
        @WebParam(partName = "parameters", name = "GprGetConfigLottoIUVCodiceAsr", targetNamespace = "http://ws.wso2.org/dataservice")
        GprGetConfigLottoIUVCodiceAsr parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "LmsGetRimborsiPagamentoByPratica", action = "urn:LmsGetRimborsiPagamentoByPratica")
    @Action(input = "urn:LmsGetRimborsiPagamentoByPratica", output = "urn:LmsGetRimborsiPagamentoByPraticaResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:LmsGetRimborsiPagamentoByPraticaDataServiceFault")})
    @RequestWrapper(localName = "LmsGetRimborsiPagamentoByPratica", targetNamespace = "http://csi.it", className = "it.csi.LmsGetRimborsiPagamentoByPratica")
    @ResponseWrapper(localName = "elencoRimborsiPagamento", targetNamespace = "http://csi.it", className = "it.csi.ElencoRimborsiPagamento")
    @WebResult(name = "RIMBORSO_PAGAMENTO", targetNamespace = "http://csi.it")
    public java.util.List<it.csi.RIMBORSOPAGAMENTO> lmsGetRimborsiPagamentoByPratica(
        @WebParam(name = "id_prenotazione", targetNamespace = "http://csi.it")
        java.math.BigDecimal idPrenotazione
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEstrazioneListaTicketMetadatiGPANested", action = "urn:GprEstrazioneListaTicketMetadatiGPANested")
    @Action(input = "urn:GprEstrazioneListaTicketMetadatiGPANested", output = "urn:GprEstrazioneListaTicketMetadatiGPANestedResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEstrazioneListaTicketMetadatiGPANestedDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ELENCO_PRESTAZIONI", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public ELENCOPRESTAZIONI gprEstrazioneListaTicketMetadatiGPANested(
        @WebParam(partName = "parameters", name = "GprEstrazioneListaTicketMetadatiGPANested", targetNamespace = "http://ws.wso2.org/dataservice")
        GprEstrazioneListaTicketMetadatiGPANested parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprGetDatiSensibiliUtenteAziendale", action = "urn:GprGetDatiSensibiliUtenteAziendale")
    @Action(input = "urn:GprGetDatiSensibiliUtenteAziendale", output = "urn:GprGetDatiSensibiliUtenteAziendaleResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprGetDatiSensibiliUtenteAziendaleDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetDatiSensibiliUtenteAziendaleResult", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public GetDatiSensibiliUtenteAziendaleResult gprGetDatiSensibiliUtenteAziendale(
        @WebParam(partName = "parameters", name = "GprGetDatiSensibiliUtenteAziendale", targetNamespace = "http://ws.wso2.org/dataservice")
        GprGetDatiSensibiliUtenteAziendale parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprRecuperoListaTicketMetadati", action = "urn:GprRecuperoListaTicketMetadati")
    @Action(input = "urn:GprRecuperoListaTicketMetadati", output = "urn:GprRecuperoListaTicketMetadatiResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprRecuperoListaTicketMetadatiDataServiceFault")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "RecuperoListaTicketMetadatiResult", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public RecuperoListaTicketMetadatiResult gprRecuperoListaTicketMetadati(
        @WebParam(partName = "parameters", name = "GprRecuperoListaTicketMetadati", targetNamespace = "http://ws.wso2.org/dataservice")
        GprRecuperoListaTicketMetadati parameters
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprEndpointPerGetListaTicketCF", action = "urn:GprEndpointPerGetListaTicketCF")
    @Action(input = "urn:GprEndpointPerGetListaTicketCF", output = "urn:GprEndpointPerGetListaTicketCFResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprEndpointPerGetListaTicketCFDataServiceFault")})
    @RequestWrapper(localName = "GprEndpointPerGetListaTicketCF", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetListaTicketCF")
    @ResponseWrapper(localName = "GprEndpointPerGetListaTicketCF", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprEndpointPerGetListaTicketCF")
    public void gprEndpointPerGetListaTicketCF(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ASR", targetNamespace = "http://ws.wso2.org/dataservice")
        javax.xml.ws.Holder<java.lang.String> asr
    ) throws DataServiceFault;

    @WebMethod(operationName = "GprRichiestaLottoIUVMulti", action = "urn:GprRichiestaLottoIUVMulti")
    @Action(input = "urn:GprRichiestaLottoIUVMulti", output = "urn:GprRichiestaLottoIUVMultiResponse", fault = {@FaultAction(className = DataServiceFault.class, value = "urn:GprRichiestaLottoIUVMultiDataServiceFault")})
    @RequestWrapper(localName = "GprRichiestaLottoIUVMulti", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprRichiestaLottoIUVMulti")
    @ResponseWrapper(localName = "GprRichiestaLottoIUVMultiResponse", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GprRichiestaLottoIUVMultiResponse")
    @WebResult(name = "LOTTO_IUV", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.LOTTOIUV> gprRichiestaLottoIUVMulti(
        @WebParam(name = "codice_asr", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String codiceAsr,
        @WebParam(name = "codice_versamento", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String codiceVersamento,
        @WebParam(name = "uuid_gpr", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String uuidGpr,
        @WebParam(name = "uuid_gpa", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String uuidGpa,
        @WebParam(name = "iuv_richiesti", targetNamespace = "http://ws.wso2.org/dataservice")
        java.math.BigDecimal iuvRichiesti,
        @WebParam(name = "esito_prec", targetNamespace = "http://ws.wso2.org/dataservice")
        java.math.BigDecimal esitoPrec
    ) throws DataServiceFault;
}
