/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanpresc.soap.dma.dettaglioricettaprescritta;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-11-15T09:27:11.448+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class CCDettaglioRicettaPrescrittaService_CCDettaglioRicettaPrescrittaServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "CCDettaglioRicettaPrescrittaService");

    private CCDettaglioRicettaPrescrittaService_CCDettaglioRicettaPrescrittaServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CCDettaglioRicettaPrescrittaService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CCDettaglioRicettaPrescrittaService_Service ss = new CCDettaglioRicettaPrescrittaService_Service(wsdlURL, SERVICE_NAME);
        CCDettaglioRicettaPrescrittaService port = ss.getCCDettaglioRicettaPrescrittaServicePort();  
        
        {
        System.out.println("Invoking dettaglioRicettaPrescritta...");
        it.csi.apisan.apisanpresc.soap.dma.dettaglioricettaprescritta.DettaglioRicettaPrescrittaRequest _dettaglioRicettaPrescritta_dettaglioRicettaPrescrittaRequest = new it.csi.apisan.apisanpresc.soap.dma.dettaglioricettaprescritta.DettaglioRicettaPrescrittaRequest();
        it.csi.apisan.apisanpresc.soap.dma.dettaglioricettaprescritta.DettaglioRicettaPrescrittaResponse _dettaglioRicettaPrescritta__return = port.dettaglioRicettaPrescritta(_dettaglioRicettaPrescritta_dettaglioRicettaPrescrittaRequest);
        System.out.println("dettaglioRicettaPrescritta.result=" + _dettaglioRicettaPrescritta__return);


        }

        System.exit(0);
    }

}
