/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanpresc.soap.dma.dettaglioricettaprescritta;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.apisan.apisanpresc.common.ApiSanPrescConstants;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-11-15T09:27:11.493+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "CCDettaglioRicettaPrescrittaService", 
                  wsdlLocation = "file:/C:/Work/CSIPiemonte/APISAN/apisanpresc/src/java/it/csi/apisan/apisanpresc/soap/dma/dettaglioricettaprescritta/CCDettaglioRicettaPrescrittaService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class CCDettaglioRicettaPrescrittaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "CCDettaglioRicettaPrescrittaService");
    public final static QName CCDettaglioRicettaPrescrittaServicePort = new QName("http://dmacc.csi.it/", "CCDettaglioRicettaPrescrittaServicePort");
    static {
        URL url = null;
        try {
            url = new URL(ApiSanPrescConstants.DMA_DETTAGLIORICETTAPRESCRITTA_WSDL);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CCDettaglioRicettaPrescrittaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Work/CSIPiemonte/APISAN/apisanpresc/src/java/it/csi/apisan/apisanpresc/soap/dma/dettaglioricettaprescritta/CCDettaglioRicettaPrescrittaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CCDettaglioRicettaPrescrittaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCDettaglioRicettaPrescrittaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCDettaglioRicettaPrescrittaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCDettaglioRicettaPrescrittaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCDettaglioRicettaPrescrittaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CCDettaglioRicettaPrescrittaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CCDettaglioRicettaPrescrittaService
     */
    @WebEndpoint(name = "CCDettaglioRicettaPrescrittaServicePort")
    public CCDettaglioRicettaPrescrittaService getCCDettaglioRicettaPrescrittaServicePort() {
        return super.getPort(CCDettaglioRicettaPrescrittaServicePort, CCDettaglioRicettaPrescrittaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCDettaglioRicettaPrescrittaService
     */
    @WebEndpoint(name = "CCDettaglioRicettaPrescrittaServicePort")
    public CCDettaglioRicettaPrescrittaService getCCDettaglioRicettaPrescrittaServicePort(WebServiceFeature... features) {
        return super.getPort(CCDettaglioRicettaPrescrittaServicePort, CCDettaglioRicettaPrescrittaService.class, features);
    }

}
