/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanpresc.soap.pro.elenconrenascosti;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-09-24T15:17:30.612+02:00
 * Generated source version: 2.7.14
 * 
 */
public final class ElencoNreNascostiService_ElencoNreNascostiServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmapro.csi.it/", "ElencoNreNascostiService");

    private ElencoNreNascostiService_ElencoNreNascostiServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ElencoNreNascostiService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ElencoNreNascostiService_Service ss = new ElencoNreNascostiService_Service(wsdlURL, SERVICE_NAME);
        ElencoNreNascostiService port = ss.getElencoNreNascostiServicePort();  
        
        {
        System.out.println("Invoking elencoNreNascosti...");
        it.csi.apisan.apisanpresc.soap.pro.elenconrenascosti.ElencoNreNascosti _elencoNreNascosti_elencoNreNascostiRequest = new it.csi.apisan.apisanpresc.soap.pro.elenconrenascosti.ElencoNreNascosti();
        it.csi.apisan.apisanpresc.soap.pro.elenconrenascosti.ElencoNreNascostiResponse _elencoNreNascosti__return = port.elencoNreNascosti(_elencoNreNascosti_elencoNreNascostiRequest);
        System.out.println("elencoNreNascosti.result=" + _elencoNreNascosti__return);


        }

        System.exit(0);
    }

}
