/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanfse.integration.arruolamento.dmacc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-09-09T15:25:23.713+02:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "Exception", targetNamespace = "http://dmacc.csi.it/")
public class Exception_Exception extends java.lang.Exception {
    
    private it.csi.apisan.apisanfse.integration.arruolamento.dmacc.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, it.csi.apisan.apisanfse.integration.arruolamento.dmacc.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, it.csi.apisan.apisanfse.integration.arruolamento.dmacc.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public it.csi.apisan.apisanfse.integration.arruolamento.dmacc.Exception getFaultInfo() {
        return this.exception;
    }
}
