/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.dma.farmab.interfacews.msg.getdevicecertificato;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-12-01T10:54:22.008+01:00
 * Generated source version: 2.7.14
 * 
 */
public final class GetDeviceCertificatoService_GetDeviceCertificatoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/", "GetDeviceCertificatoServiceImplService");

    private GetDeviceCertificatoService_GetDeviceCertificatoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetDeviceCertificatoServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetDeviceCertificatoServiceImplService ss = new GetDeviceCertificatoServiceImplService(wsdlURL, SERVICE_NAME);
        GetDeviceCertificatoService port = ss.getGetDeviceCertificatoPort();  
        
        {
        System.out.println("Invoking getDeviceCertificato...");
        it.csi.dma.farmab.interfacews.msg.getdevicecertificato.Richiedente _getDeviceCertificato_richiedente = null;
        java.lang.String _getDeviceCertificato_cfCittadino = "";
        javax.xml.ws.Holder<java.lang.String> _getDeviceCertificato_esito = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.getdevicecertificato.ElencoErroriType> _getDeviceCertificato_elencoErrori = new javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.getdevicecertificato.ElencoErroriType>();
        javax.xml.ws.Holder<java.lang.String> _getDeviceCertificato_statoCertificazione = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.getdevicecertificato.CertificazioneType> _getDeviceCertificato_datiCertificazione = new javax.xml.ws.Holder<it.csi.dma.farmab.interfacews.msg.getdevicecertificato.CertificazioneType>();
        port.getDeviceCertificato(_getDeviceCertificato_richiedente, _getDeviceCertificato_cfCittadino, _getDeviceCertificato_esito, _getDeviceCertificato_elencoErrori, _getDeviceCertificato_statoCertificazione, _getDeviceCertificato_datiCertificazione);

        System.out.println("getDeviceCertificato._getDeviceCertificato_esito=" + _getDeviceCertificato_esito.value);
        System.out.println("getDeviceCertificato._getDeviceCertificato_elencoErrori=" + _getDeviceCertificato_elencoErrori.value);
        System.out.println("getDeviceCertificato._getDeviceCertificato_statoCertificazione=" + _getDeviceCertificato_statoCertificazione.value);
        System.out.println("getDeviceCertificato._getDeviceCertificato_datiCertificazione=" + _getDeviceCertificato_datiCertificazione.value);

        }

        System.exit(0);
    }

}
