/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.dma.farmab.interfacews.msg.getdevicecertificato;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-12-01T10:54:22.054+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/", name = "GetDeviceCertificatoService")
@XmlSeeAlso({ObjectFactory.class})
public interface GetDeviceCertificatoService {

    @WebMethod
    @RequestWrapper(localName = "getDeviceCertificato", targetNamespace = "http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/", className = "it.csi.dma.farmab.interfacews.msg.getdevicecertificato.GetDeviceCertificatoRequest")
    @ResponseWrapper(localName = "getDeviceCertificatoResponse", targetNamespace = "http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/", className = "it.csi.dma.farmab.interfacews.msg.getdevicecertificato.GetDeviceCertificatoResponse")
    public void getDeviceCertificato(
        @WebParam(name = "richiedente", targetNamespace = "http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/")
        it.csi.dma.farmab.interfacews.msg.getdevicecertificato.Richiedente richiedente,
        @WebParam(name = "cfCittadino", targetNamespace = "http://getdevicecertificato.msg.interfacews.farmab.dma.csi.it/")
        java.lang.String cfCittadino,
        @WebParam(mode = WebParam.Mode.OUT, name = "esito", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> esito,
        @WebParam(mode = WebParam.Mode.OUT, name = "elencoErrori", targetNamespace = "")
        javax.xml.ws.Holder<ElencoErroriType> elencoErrori,
        @WebParam(mode = WebParam.Mode.OUT, name = "statoCertificazione", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> statoCertificazione,
        @WebParam(mode = WebParam.Mode.OUT, name = "datiCertificazione", targetNamespace = "")
        javax.xml.ws.Holder<CertificazioneType> datiCertificazione
    );
}
