/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.apisan.apisanpresc.soap.pro.logaudit;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2019-09-24T16:00:08.608+02:00
 * Generated source version: 2.7.14
 * 
 */
public final class LogAuditService_LogAuditServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmapro.csi.it/", "LogAuditService");

    private LogAuditService_LogAuditServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LogAuditService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LogAuditService_Service ss = new LogAuditService_Service(wsdlURL, SERVICE_NAME);
        LogAuditService port = ss.getLogAuditServicePort();  
        
        {
        System.out.println("Invoking logAudit...");
        it.csi.apisan.apisanpresc.soap.pro.logaudit.LogAuditRequest _logAudit_logAuditRequest = new it.csi.apisan.apisanpresc.soap.pro.logaudit.LogAuditRequest();
        it.csi.apisan.apisanpresc.soap.pro.logaudit.LogAuditResponse _logAudit__return = port.logAudit(_logAudit_logAuditRequest);
        System.out.println("logAudit.result=" + _logAudit__return);


        }

        System.exit(0);
    }

}
