/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.aura.auraws.services.central.ricercateam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RicercaTEAMSoap", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RicercaTEAMSoap {


    /**
     * 
     * @param cf
     * @param team
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RicercaTEAM", action = "http://RicercaTEAM.central.services.auraws.aura.csi.it/AURA.WS.RicercaTEAM.RicercaTEAM")
    @WebResult(name = "RicercaTEAMResult", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "RicercaTEAM", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.ricercateam.RicercaTEAM")
    @ResponseWrapper(localName = "RicercaTEAMResponse", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.ricercateam.RicercaTEAMResponse")
    public String ricercaTEAM(
        @WebParam(name = "CF", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it")
        String cf,
        @WebParam(name = "TEAM", targetNamespace = "http://RicercaTEAM.central.services.auraws.aura.csi.it")
        String team);

}
