/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.esenzioni.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-01-18T13:19:14.598+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "EsenzioniService")
@XmlSeeAlso({it.csi.apisan.apisanfse.integration.esenzioni.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EsenzioniService {

    @WebMethod
    @WebResult(name = "getEsenzioniResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getEsenzioniResponse")
    public EsenzioniResponse getEsenzioni(
        @WebParam(partName = "getEsenzioni", name = "getEsenzioni", targetNamespace = "http://dmacc.csi.it/")
        EsenzioniRequest getEsenzioni
    );
}
