/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.apisan.apisanfse.integration.documenti.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-07-21T14:42:53.904+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "DocumentiService")
@XmlSeeAlso({it.csi.apisan.apisanfse.integration.documenti.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DocumentiService {

    @WebMethod(action = "http://dma.csi.it/DocumentiService/registraAvvenutoRitiro")
    @WebResult(name = "registraAvvenutoRitiroResponse", targetNamespace = "http://dmacc.csi.it/", partName = "registraAvvenutoRitiroResponse")
    public RegistraAvvenutoRitiroResponse registraAvvenutoRitiro(
        @WebParam(partName = "registraAvvenutoRitiro", name = "registraAvvenutoRitiro", targetNamespace = "http://dmacc.csi.it/")
        RegistraAvvenutoRitiroRequest registraAvvenutoRitiro
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getSoloEpisodi")
    @WebResult(name = "GetSoloEpisodiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "GetSoloEpisodiResponse")
    public GetSoloEpisodiResponse getSoloEpisodi(
        @WebParam(partName = "getSoloEpisodi", name = "getSoloEpisodi", targetNamespace = "http://dmacc.csi.it/")
        GetSoloEpisodiRequest getSoloEpisodi
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getMieiRefertiDocs")
    @WebResult(name = "getMieiRefertiDocsResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getMieiRefertiDocsResponse")
    public GetRefertiResponse getMieiRefertiDocs(
        @WebParam(partName = "getMieiRefertiDocs", name = "getMieiRefertiDocs", targetNamespace = "http://dmacc.csi.it/")
        GetRefertiRequest getMieiRefertiDocs
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDettaglioDocumento")
    @WebResult(name = "GetDettaglioDocumentoResponse", targetNamespace = "http://dmacc.csi.it/", partName = "GetDettaglioDocumentoResponse")
    public GetDettaglioDocumentoResponse getDettaglioDocumento(
        @WebParam(partName = "getDettaglioDocumento", name = "getDettaglioDocumento", targetNamespace = "http://dmacc.csi.it/")
        GetDettaglioDocumentoRequest getDettaglioDocumento
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDocumento")
    @WebResult(name = "getDocumentoResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getDocumentoResponse")
    public GetDocumentoResponse getDocumento(
        @WebParam(partName = "getDocumento", name = "getDocumento", targetNamespace = "http://dmacc.csi.it/")
        GetDocumento getDocumento
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDocumentiEpisodio")
    @WebResult(name = "GetDocumentiEpisodioResponse", targetNamespace = "http://dmacc.csi.it/", partName = "GetDocumentiEpisodioResponse")
    public GetDocumentiEpisodioResponse getDocumentiEpisodio(
        @WebParam(partName = "getDocumentiEpisodio", name = "getDocumentiEpisodio", targetNamespace = "http://dmacc.csi.it/")
        GetDocumentiEpisodioRequest getDocumentiEpisodio
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getTuttiDocs")
    @WebResult(name = "getTuttiDocsResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getTuttiDocsResponse")
    public GetTuttiDocsResponse getTuttiDocs(
        @WebParam(partName = "getTuttiDocs", name = "getTuttiDocs", targetNamespace = "http://dmacc.csi.it/")
        GetTuttiDocsRequest getTuttiDocs
    );

    @WebMethod
    @WebResult(name = "smediazioneDocumentiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "smediazioneDocumentiResponse")
    public SmediazioneDocumentiResponse smediazioneDocumenti(
        @WebParam(partName = "smediazioneDocumenti", name = "smediazioneDocumentiRequest", targetNamespace = "http://dmacc.csi.it/")
        SmediazioneDocumentiRequest smediazioneDocumenti
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getMieiReferti")
    @WebResult(name = "getMieiRefertiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getMieiRefertiResponse")
    public GetRefertiResponse getMieiReferti(
        @WebParam(partName = "getMieiReferti", name = "getMieiReferti", targetNamespace = "http://dmacc.csi.it/")
        GetRefertiRequest getMieiReferti
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDocumentiCorrelati")
    @WebResult(name = "getDocumentiCorrelatiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getDocumentiCorrelatiResponse")
    public GetDocumentiCorrelatiResponse getDocumentiCorrelati(
        @WebParam(partName = "getDocumentiCorrelati", name = "getDocumentiCorrelati", targetNamespace = "http://dmacc.csi.it/")
        GetDocumentiCorrelatiRequest getDocumentiCorrelati
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/verificaDocumentoScaricabile")
    @WebResult(name = "verificaDocumentoScaricabileResponse", targetNamespace = "http://dmacc.csi.it/", partName = "verificaDocumentoScaricabileResponse")
    public VerificaDocumentoScaricabileResponse verificaDocumentoScaricabile(
        @WebParam(partName = "verificaDocumentoScaricabile", name = "verificaDocumentoScaricabile", targetNamespace = "http://dmacc.csi.it/")
        VerificaDocumentoScaricabileRequest verificaDocumentoScaricabile
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDocumentiCorrelatiOSC")
    @WebResult(name = "getDocumentiCorrelatiOSCResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getDocumentiCorrelatiOSCResponse")
    public GetDocumentiCorrelatiOSCResponse getDocumentiCorrelatiOSC(
        @WebParam(partName = "getDocumentiCorrelatiOSC", name = "getDocumentiCorrelatiOSC", targetNamespace = "http://dmacc.csi.it/")
        GetDocumentiCorrelatiOSCRequest getDocumentiCorrelatiOSC
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getConteggi")
    @WebResult(name = "GetConteggiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "GetConteggiResponse")
    public GetConteggiResponse getConteggi(
        @WebParam(partName = "getConteggi", name = "getConteggi", targetNamespace = "http://dmacc.csi.it/")
        GetConteggiRequest getConteggi
    );
}
