/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.dma.farmab.interfacews.msg.setfarmaciaabituale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-11-19T15:27:06.908+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "SetFarmaciaAbitualeServiceImplService", 
                  wsdlLocation = "file:/C:/Users/2048/AppData/Local/Temp/tempdir3707828821871232788.tmp/SetFarmaciaAbitualeService_1.wsdl",
                  targetNamespace = "http://setfarmaciaabituale.msg.interfacews.farmab.dma.csi.it/") 
public class SetFarmaciaAbitualeServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://setfarmaciaabituale.msg.interfacews.farmab.dma.csi.it/", "SetFarmaciaAbitualeServiceImplService");
    public final static QName SetFarmaciaAbitualePort = new QName("http://setfarmaciaabituale.msg.interfacews.farmab.dma.csi.it/", "SetFarmaciaAbitualePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/2048/AppData/Local/Temp/tempdir3707828821871232788.tmp/SetFarmaciaAbitualeService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SetFarmaciaAbitualeServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/2048/AppData/Local/Temp/tempdir3707828821871232788.tmp/SetFarmaciaAbitualeService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SetFarmaciaAbitualeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SetFarmaciaAbitualeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SetFarmaciaAbitualeServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetFarmaciaAbitualeServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetFarmaciaAbitualeServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SetFarmaciaAbitualeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SetFarmaciaAbitualeService
     */
    @WebEndpoint(name = "SetFarmaciaAbitualePort")
    public SetFarmaciaAbitualeService getSetFarmaciaAbitualePort() {
        return super.getPort(SetFarmaciaAbitualePort, SetFarmaciaAbitualeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SetFarmaciaAbitualeService
     */
    @WebEndpoint(name = "SetFarmaciaAbitualePort")
    public SetFarmaciaAbitualeService getSetFarmaciaAbitualePort(WebServiceFeature... features) {
        return super.getPort(SetFarmaciaAbitualePort, SetFarmaciaAbitualeService.class, features);
    }

}
