/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.gpr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-04-17T10:41:07.973+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "proxyGPR", 
                  wsdlLocation = "https://tst-wfcer-gpa.isan.csi.it/wso039/services/proxyGPR?wsdl",
                  targetNamespace = "http://csi.it") 
public class ProxyGPR extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://csi.it", "proxyGPR");
    public final static QName ProxyGPRHttpsEndpoint = new QName("http://csi.it", "proxyGPRHttpsEndpoint");
    public final static QName ProxyGPRHttpSoap11Endpoint = new QName("http://csi.it", "proxyGPRHttpSoap11Endpoint");
    public final static QName ProxyGPRHttpSoap12Endpoint = new QName("http://csi.it", "proxyGPRHttpSoap12Endpoint");
    public final static QName ProxyGPRHttpsSoap11Endpoint = new QName("http://csi.it", "proxyGPRHttpsSoap11Endpoint");
    public final static QName ProxyGPRHttpEndpoint = new QName("http://csi.it", "proxyGPRHttpEndpoint");
    public final static QName ProxyGPRHttpsSoap12Endpoint = new QName("http://csi.it", "proxyGPRHttpsSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-wfcer-gpa.isan.csi.it/wso039/services/proxyGPR?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProxyGPR.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://tst-wfcer-gpa.isan.csi.it/wso039/services/proxyGPR?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProxyGPR(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProxyGPR(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyGPR() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProxyGPR(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProxyGPR(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProxyGPR(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsEndpoint")
    public ProxyGPRPortType getProxyGPRHttpsEndpoint() {
        return super.getPort(ProxyGPRHttpsEndpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsEndpoint")
    public ProxyGPRPortType getProxyGPRHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpsEndpoint, ProxyGPRPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpSoap11Endpoint")
    public ProxyGPRPortType getProxyGPRHttpSoap11Endpoint() {
        return super.getPort(ProxyGPRHttpSoap11Endpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpSoap11Endpoint")
    public ProxyGPRPortType getProxyGPRHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpSoap11Endpoint, ProxyGPRPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpSoap12Endpoint")
    public ProxyGPRPortType getProxyGPRHttpSoap12Endpoint() {
        return super.getPort(ProxyGPRHttpSoap12Endpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpSoap12Endpoint")
    public ProxyGPRPortType getProxyGPRHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpSoap12Endpoint, ProxyGPRPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsSoap11Endpoint")
    public ProxyGPRPortType getProxyGPRHttpsSoap11Endpoint() {
        return super.getPort(ProxyGPRHttpsSoap11Endpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsSoap11Endpoint")
    public ProxyGPRPortType getProxyGPRHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpsSoap11Endpoint, ProxyGPRPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpEndpoint")
    public ProxyGPRPortType getProxyGPRHttpEndpoint() {
        return super.getPort(ProxyGPRHttpEndpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpEndpoint")
    public ProxyGPRPortType getProxyGPRHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpEndpoint, ProxyGPRPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsSoap12Endpoint")
    public ProxyGPRPortType getProxyGPRHttpsSoap12Endpoint() {
        return super.getPort(ProxyGPRHttpsSoap12Endpoint, ProxyGPRPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyGPRPortType
     */
    @WebEndpoint(name = "proxyGPRHttpsSoap12Endpoint")
    public ProxyGPRPortType getProxyGPRHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(ProxyGPRHttpsSoap12Endpoint, ProxyGPRPortType.class, features);
    }

}
