/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-06-03T16:52:25.876+02:00
 * Generated source version: 2.7.14
 * 
 */
public final class IPtwsrvServiceAvvisoPagamentoWS_PtwsrvavvisopagamentoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ptwsrvavvisopagamento.webservice.business.ptwsrv.csi.it/", "ptwsrvavvisopagamento");

    private IPtwsrvServiceAvvisoPagamentoWS_PtwsrvavvisopagamentoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Ptwsrvavvisopagamento.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Ptwsrvavvisopagamento ss = new Ptwsrvavvisopagamento(wsdlURL, SERVICE_NAME);
        IPtwsrvServiceAvvisoPagamentoWS port = ss.getPtwsrvavvisopagamentoPort();  
        
        {
        System.out.println("Invoking avvisoPagamento...");
        java.util.List<it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.ItemStampaAvvisoPagamento> _avvisoPagamento_arg0 = null;
        try {
            it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.OutputAvvisoPagamento _avvisoPagamento__return = port.avvisoPagamento(_avvisoPagamento_arg0);
            System.out.println("avvisoPagamento.result=" + _avvisoPagamento__return);

        } catch (AvvisoPagamentoException_Exception e) { 
            System.out.println("Expected exception: AvvisoPagamentoException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
