/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2020-06-03T16:52:25.941+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://ptwsrvavvisopagamento.webservice.business.ptwsrv.csi.it/", name = "IPtwsrvServiceAvvisoPagamentoWS")
@XmlSeeAlso({ObjectFactory.class})
public interface IPtwsrvServiceAvvisoPagamentoWS {

    @WebMethod
    @RequestWrapper(localName = "avvisoPagamento", targetNamespace = "http://ptwsrvavvisopagamento.webservice.business.ptwsrv.csi.it/", className = "it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.AvvisoPagamento")
    @ResponseWrapper(localName = "avvisoPagamentoResponse", targetNamespace = "http://ptwsrvavvisopagamento.webservice.business.ptwsrv.csi.it/", className = "it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.AvvisoPagamentoResponse")
    @WebResult(name = "outputAvvisoPagamento", targetNamespace = "")
    public it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.OutputAvvisoPagamento avvisoPagamento(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<it.csi.ptwsrv.business.webservice.ptwsrvavvisopagamento.ItemStampaAvvisoPagamento> arg0
    ) throws AvvisoPagamentoException_Exception;
}
