/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.celiachia.celiachiabesrv.business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-02-11T12:17:31.179+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "InterfacciaCeliachiaBeSrv", 
                  wsdlLocation = "file:/C:/Users/2048/AppData/Local/Temp/tempdir5746218112955211123.tmp/InterfacciaCeliachiaBeSrv_1.wsdl",
                  targetNamespace = "http://business.celiachiabesrv.celiachia.csi.it") 
public class InterfacciaCeliachiaBeSrv extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrv");
    public final static QName InterfacciaCeliachiaBeSrvHttpEndpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpEndpoint");
    public final static QName InterfacciaCeliachiaBeSrvHttpSoap12Endpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpSoap12Endpoint");
    public final static QName InterfacciaCeliachiaBeSrvHttpSoap11Endpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpSoap11Endpoint");
    public final static QName InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint");
    public final static QName InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint");
    public final static QName InterfacciaCeliachiaBeSrvHttpsEndpoint = new QName("http://business.celiachiabesrv.celiachia.csi.it", "InterfacciaCeliachiaBeSrvHttpsEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/2048/AppData/Local/Temp/tempdir5746218112955211123.tmp/InterfacciaCeliachiaBeSrv_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterfacciaCeliachiaBeSrv.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/2048/AppData/Local/Temp/tempdir5746218112955211123.tmp/InterfacciaCeliachiaBeSrv_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterfacciaCeliachiaBeSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterfacciaCeliachiaBeSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfacciaCeliachiaBeSrv() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterfacciaCeliachiaBeSrv(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterfacciaCeliachiaBeSrv(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterfacciaCeliachiaBeSrv(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpEndpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpEndpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpEndpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpEndpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpEndpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }
    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpSoap12Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpSoap12Endpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpSoap12Endpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpSoap12Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpSoap12Endpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }
    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpSoap11Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpSoap11Endpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpSoap11Endpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpSoap11Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpSoap11Endpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }
    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsSoap11Endpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsSoap11Endpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }
    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsSoap12Endpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsSoap12Endpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }
    /**
     *
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsEndpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsEndpoint() {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsEndpoint, InterfacciaCeliachiaBeSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacciaCeliachiaBeSrvPortType
     */
    @WebEndpoint(name = "InterfacciaCeliachiaBeSrvHttpsEndpoint")
    public InterfacciaCeliachiaBeSrvPortType getInterfacciaCeliachiaBeSrvHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(InterfacciaCeliachiaBeSrvHttpsEndpoint, InterfacciaCeliachiaBeSrvPortType.class, features);
    }

}
