/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/

package it.csi.dma.dmaclbluc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-04-22T16:01:59.374+02:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "DmaclLXmlMessaggiDaoException", targetNamespace = "http://dmaclbluc.dma.csi.it/")
public class DmaclLXmlMessaggiDaoException_Exception extends Exception {
    
    private it.csi.dma.dmaclbluc.DmaclLXmlMessaggiDaoException dmaclLXmlMessaggiDaoException;

    public DmaclLXmlMessaggiDaoException_Exception() {
        super();
    }
    
    public DmaclLXmlMessaggiDaoException_Exception(String message) {
        super(message);
    }
    
    public DmaclLXmlMessaggiDaoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DmaclLXmlMessaggiDaoException_Exception(String message, it.csi.dma.dmaclbluc.DmaclLXmlMessaggiDaoException dmaclLXmlMessaggiDaoException) {
        super(message);
        this.dmaclLXmlMessaggiDaoException = dmaclLXmlMessaggiDaoException;
    }

    public DmaclLXmlMessaggiDaoException_Exception(String message, it.csi.dma.dmaclbluc.DmaclLXmlMessaggiDaoException dmaclLXmlMessaggiDaoException, Throwable cause) {
        super(message, cause);
        this.dmaclLXmlMessaggiDaoException = dmaclLXmlMessaggiDaoException;
    }

    public it.csi.dma.dmaclbluc.DmaclLXmlMessaggiDaoException getFaultInfo() {
        return this.dmaclLXmlMessaggiDaoException;
    }
}
