/*******************************************************************************

* Copyright Regione Piemonte - 2022

* SPDX-License-Identifier: EUPL-1.2

******************************************************************************/
package it.csi.dma.dmaclbluc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-04-22T16:01:59.389+02:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "TaccuinoServiceImplService", 
                  wsdlLocation = "file:/C:/Users/Sestu/AppData/Local/Temp/tempdir2433952076332533194.tmp/TaccuinoService_1.wsdl",
                  targetNamespace = "http://dmaclbluc.dma.csi.it/") 
public class TaccuinoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmaclbluc.dma.csi.it/", "TaccuinoServiceImplService");
    public final static QName TaccuinoServicePort = new QName("http://dmaclbluc.dma.csi.it/", "TaccuinoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Sestu/AppData/Local/Temp/tempdir2433952076332533194.tmp/TaccuinoService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaccuinoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Sestu/AppData/Local/Temp/tempdir2433952076332533194.tmp/TaccuinoService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaccuinoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaccuinoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaccuinoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaccuinoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaccuinoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaccuinoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TaccuinoService
     */
    @WebEndpoint(name = "TaccuinoServicePort")
    public TaccuinoService getTaccuinoServicePort() {
        return super.getPort(TaccuinoServicePort, TaccuinoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaccuinoService
     */
    @WebEndpoint(name = "TaccuinoServicePort")
    public TaccuinoService getTaccuinoServicePort(WebServiceFeature... features) {
        return super.getPort(TaccuinoServicePort, TaccuinoService.class, features);
    }

}
